'use strict';

const teams=[['ANA','Anaheim Ducks'],['BOS','Boston Bruins'],['BUF','Buffalo Sabres'],['CGY','Calgary Flames'],['CAR','Carolina Hurricanes'],['CHI','Chicago Blackhawks'],['COL','Colorado Avalanche'],['CBJ','Columbus Blue Jackets'],['DAL','Dallas Stars'],['DET','Detroit Red Wings'],['EDM','Edmonton Oilers'],['FLA','Florida Panthers'],['LAK','Los Angeles Kings'],['MIN','Minnesota Wild'],['MTL','Montreal Canadiens'],['NSH','Nashville Predators'],['NJD','New Jersey Devils'],['NYI','New York Islanders'],['NYR','New York Rangers'],['OTT','Ottawa Senators'],['PHI','Philadelphia Flyers'],['PIT','Pittsburgh Penguins'],['SJS','San Jose Sharks'],['SEA','Seattle Kraken'],['STL','St. Louis Blues'],['TBL','Tampa Bay Lightning'],['TOR','Toronto Maple Leafs'],['UTA','Utah Mammoth'],['VAN','Vancouver Canucks'],['VGK','Vegas Golden Knights'],['WSH','Washington Capitals'],['WPG','Winnipeg Jets']];
const $=id=>document.getElementById(id),proxyServer=location.protocol.startsWith('http'),api=proxyServer?'/api/nhl/v1':'https://api-web.nhle.com/v1',searchApi=proxyServer?'/api/player-search':'https://search.d3.nhle.com/api/v1/search/player',cache=new Map(),playerSelections={stats:null,history:null};
const dateStr=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
$('scoreDate').value=dateStr(new Date());$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date());
$('opponent').innerHTML=teams.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function status(id,msg,type=''){const el=$(id);el.textContent=msg;el.className='status'+(type?' '+type:'')}
async function fetchJson(url,timeout=4500){const response=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!response.ok){let detail='';try{const body=await response.json();detail=body.error||body.message||''}catch{}throw Error(detail||`Request failed (HTTP ${response.status})`)}return response.json()}
async function get(path,timeout=proxyServer?10000:3500){const url=path.startsWith('http')?path:proxyServer&&path.startsWith('/api/')?path:api+path;if(cache.has(url))return cache.get(url);const request=(async()=>{try{return await fetchJson(url,timeout)}catch(e){if(proxyServer){if(e.name==='TimeoutError')throw Error('The local NHL request timed out. Try again in a moment.');if(e instanceof TypeError)throw Error('Cannot reach the local Puck Props server. Close older Puck Props server windows, then launch start.bat again.');throw e}const relays=['https://api.codetabs.com/v1/proxy?quest='+encodeURIComponent(url),'https://api.allorigins.win/raw?url='+encodeURIComponent(url)];try{return await Promise.any(relays.map(relay=>fetchJson(relay,4500)))}catch{throw Error('The NHL data service could not be reached. For reliable local access, launch the app with start.bat or run node server.js.')}}})();cache.set(url,request);try{return await request}catch(e){cache.delete(url);throw e}}
function busy(btn,on,label){if(on){btn.dataset.label=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.label||btn.textContent;btn.disabled=false}}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['scores','player','history','teams','picks','saved'].forEach(id=>$(id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='saved')renderSaved();if(b.dataset.tab==='teams'){renderTeamDirectory();if(!teamRows.length)loadTeams()}}));

async function loadScores(){const btn=$('loadScores');busy(btn,true,'Loading…');status('scoreStatus','Fetching schedule…');$('scoresOut').innerHTML='';$('boxscoreOut').innerHTML='';try{const d=await get('/score/'+encodeURIComponent($('scoreDate').value)),games=d.games||[];status('scoreStatus',games.length?`${games.length} games scheduled · Select a game to view player stats`:'No games listed for this date.',games.length?'success':'');$('scoresOut').innerHTML=games.map(g=>{const state=g.gameState==='LIVE'?'LIVE':(['OFF','FINAL'].includes(g.gameState)?'FINAL':g.startTimeUTC?new Date(g.startTimeUTC).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'Scheduled');return `<button type="button" class="game game-clickable" aria-pressed="false" data-game-id="${esc(g.id)}" aria-label="View player stats: ${esc(g.awayTeam?.abbrev||'Away')} at ${esc(g.homeTeam?.abbrev||'Home')}"><div class="gamehead"><span>${esc(g.gameDate||'')}</span><span>${esc(state)}</span></div><div class="teamline"><div class="teamname">${g.awayTeam?.logo?`<img src="${esc(g.awayTeam.logo)}" alt="">`:''}<span>${esc(g.awayTeam?.abbrev||'Away')}</span></div><span class="score">${g.awayTeam?.score??'—'}</span></div><div class="teamline"><div class="teamname">${g.homeTeam?.logo?`<img src="${esc(g.homeTeam.logo)}" alt="">`:''}<span>${esc(g.homeTeam?.abbrev||'Home')}</span></div><span class="score">${g.homeTeam?.score??'—'}</span></div><div class="gamefoot">${esc(g.venue?.default||'Venue to be announced')}</div><div class="game-action">View player stats →</div></button>`}).join('');document.querySelectorAll('[data-game-id]').forEach(card=>card.addEventListener('click',()=>loadGameBoxscore(card.dataset.gameId,card)))}catch(e){status('scoreStatus',e.message,'error')}finally{busy(btn,false)}}
function boxscorePlayerTable(group,players){const goalies=group==='Goalies',list=[...(players||[])].sort((a,b)=>goalies?Number(b.starter)-Number(a.starter):(num(b.points)-num(a.points)||num(b.sog)-num(a.sog)||String(a.name?.default||'').localeCompare(String(b.name?.default||''))));if(!list.length)return '<div class="empty">No player stats available.</div>';const columns=goalies?['Player','Decision','Saves','Shots against','SV%','GA','TOI']:['Player','G','A','PTS','SOG','+/-','TOI'];return `<h5>${group}</h5><div class="tablewrap"><table><thead><tr>${columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${list.map(p=>{const pct=p.savePctg==null?'—':Number(p.savePctg).toFixed(3),cells=goalies?[p.name?.default||'Goalie',p.decision||'—',p.saves??'—',p.shotsAgainst??'—',pct,p.goalsAgainst??'—',p.toi||'—']:[p.name?.default||'Player',p.goals??0,p.assists??0,p.points??0,p.sog??0,p.plusMinus??0,p.toi||'—'];return `<tr>${cells.map((value,i)=>`<td>${i===0?`<b>${esc(value)}</b>`:esc(value)}</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`}
async function loadGameBoxscore(id,card){const out=$('boxscoreOut');out.innerHTML='<div class="panel"><div class="status">Loading game player stats…</div></div>';document.querySelectorAll('[data-game-id]').forEach(node=>node.setAttribute('aria-pressed',String(node===card)));try{const d=await get(`/gamecenter/${encodeURIComponent(id)}/boxscore`,20000),stats=d.playerByGameStats||{},sides=[['awayTeam',d.awayTeam],['homeTeam',d.homeTeam]];out.innerHTML=`<div class="panel" id="boxscorePanel"><div class="panelhead"><div><h3>${esc(d.awayTeam?.abbrev||'Away')} ${d.awayTeam?.score??'—'} · ${esc(d.homeTeam?.abbrev||'Home')} ${d.homeTeam?.score??'—'}</h3><p>${esc(d.venue?.default||'Game box score')} · ${esc(d.gameDate||'')}</p></div><button class="btn" id="closeBoxscore">Close box score</button></div><div class="cards">${sides.map(([side,team])=>{const playerGroups=stats[side]||{};return `<section class="game"><h4>${esc(team?.abbrev||side)}</h4>${boxscorePlayerTable('Forwards',playerGroups.forwards)}${boxscorePlayerTable('Defense',playerGroups.defense)}${boxscorePlayerTable('Goalies',playerGroups.goalies)}</section>`}).join('')}</div></div>`;$('closeBoxscore').addEventListener('click',()=>{out.innerHTML='';document.querySelectorAll('[data-game-id]').forEach(node=>node.setAttribute('aria-pressed','false'))});out.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){out.innerHTML=`<div class="panel"><div class="panelhead"><div><h3>Game player stats</h3><p>${esc(e.message)}</p></div><button class="btn" id="closeBoxscore">Close</button></div></div>`;$('closeBoxscore').addEventListener('click',()=>{out.innerHTML=''})}}
$('loadScores').addEventListener('click',loadScores);$('scoreDate').addEventListener('change',loadScores);

function playerName(p){return p.name||p.fullName||[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||'NHL Player'}
function normalizePlayers(data){const items=Array.isArray(data)?data:(data?.players||data?.results||data?.suggestions||[]);return items.map(p=>({id:String(p.playerId??p.id??p.player_id??''),name:playerName(p),team:p.teamAbbrev||p.team?.abbrev||p.teamName||'',position:p.positionCode||p.position||'',headshot:p.headshot||p.image||''})).filter(p=>p.id&&p.name!=='NHL Player')}
function setupSearch(inputId,resultId,slot){
 const input=$(inputId),out=$(resultId);let timer;
 input.addEventListener('input',()=>{
  clearTimeout(timer);playerSelections[slot]=null;$(`${slot}Selected`).textContent='';out.innerHTML='';
  if(slot==='stats'){$('playerProfile').innerHTML='';$('playerStats').innerHTML='';$('seasonStats').innerHTML='';status('playerStatus','Search for a player by name.');}
  const q=input.value.trim();if(q.length<3)return;
  out.innerHTML='<div class="description">Searching players…</div>';
  timer=setTimeout(async()=>{
   try{
    const url=searchApi.startsWith('/')?`${searchApi}?q=${encodeURIComponent(q)}`:searchApi+'?culture=en-us&limit=12&q='+encodeURIComponent(q),items=normalizePlayers(await get(url));
    if(!items.length){out.innerHTML='<div class="description">No matching players found.</div>';return}
    out.innerHTML=items.map((p,i)=>`<button class="player-choice" type="button" data-result="${slot}-${i}">${p.headshot?`<img src="${esc(p.headshot)}" alt="" loading="lazy">`:''}<span><b>${esc(p.name)}</b><small>${esc([p.team,p.position].filter(Boolean).join(' · ')||'NHL player')}</small></span></button>`).join('');
    items.forEach((p,i)=>$(resultId).querySelector(`[data-result="${slot}-${i}"]`).addEventListener('click',()=>{selectPlayer(slot,p);if(slot==='stats')loadPlayerStats(p)}));
    const exact=slot==='stats'?items.find(p=>p.name.trim().toLocaleLowerCase()===q.toLocaleLowerCase()):null;
    if(exact){selectPlayer(slot,exact);loadPlayerStats(exact)}
   }catch(e){out.innerHTML=`<div class="description">${esc(e.message)}</div>`}
  },250)
 });
 input.addEventListener('keydown',e=>{if(e.key==='Enter'){const first=out.querySelector('.player-choice');if(first){e.preventDefault();first.click()}}})
}
function selectPlayer(slot,p){playerSelections[slot]=p;$(slot==='stats'?'statsPlayerSearch':'historyPlayerSearch').value=p.name;$(`${slot}Selected`).textContent=`Selected: ${p.name}${p.team?' · '+p.team:''}${p.position?' · '+p.position:''}`;$(slot==='stats'?'statsPlayerResults':'historyPlayerResults').innerHTML=''}
setupSearch('statsPlayerSearch','statsPlayerResults','stats');setupSearch('historyPlayerSearch','historyPlayerResults','history');

function metricRows(c){return [['Games played',c.gamesPlayed],['Goals',c.goals],['Assists',c.assists],['Points',c.points],['Shots',c.shots],['Plus / minus',c.plusMinus],['Power-play goals',c.powerPlayGoals],['Penalty minutes',c.pim],['Wins',c.wins],['Save percentage',c.savePctg!=null?Number(c.savePctg).toFixed(3):undefined],['Goals-against average',c.goalsAgainstAvg!=null?Number(c.goalsAgainstAvg).toFixed(2):undefined],['Shutouts',c.shutouts],['Saves',c.saves]].filter(x=>x[1]!==undefined&&x[1]!==null)}
function seasonTable(seasons,isGoalie){const columns=isGoalie?['Season','Team','GP','W','L','OT','SV%','GAA','SO','Saves']:['Season','Team','GP','G','A','PTS','+/-','SOG'];const cell=(s,key)=>key==='Season'?String(s.season).replace(/(\d{4})(\d{4})/,'$1–$2'):key==='Team'?(s.teamName?.default||s.teamAbbrev||'—'):key==='GP'?(s.gamesPlayed??'—'):key==='G'?(s.goals??'—'):key==='A'?(s.assists??'—'):key==='PTS'?(s.points??'—'):key==='+/-'?(s.plusMinus??'—'):key==='SOG'?(s.shots??'—'):key==='W'?(s.wins??'—'):key==='L'?(s.losses??'—'):key==='OT'?(s.otLosses??'—'):key==='SV%'?(s.savePctg!=null?Number(s.savePctg).toFixed(3):'—'):key==='GAA'?(s.goalsAgainstAvg!=null?Number(s.goalsAgainstAvg).toFixed(2):'—'):key==='SO'?(s.shutouts??'—'):s.saves??'—';return '<table><thead><tr>'+columns.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+seasons.map(s=>'<tr>'+columns.map(c=>`<td>${esc(cell(s,c))}</td>`).join('')+'</tr>').join('')+'</tbody></table>'}
async function loadPlayerStats(player=playerSelections.stats){const btn=$('loadPlayerStats');if(!player){status('playerStatus','Search for and select a player by name first.','error');return}busy(btn,true,'Loading…');status('playerStatus','Loading player stats…');$('playerProfile').innerHTML='';$('playerStats').innerHTML='';$('seasonStats').innerHTML='';try{const d=await get(`/player/${encodeURIComponent(player.id)}/landing`),career=d.careerTotals?.regularSeason||{},featured=d.featuredStats?.regularSeason?.subSeason||{};playerSelections.stats={...player,name:[d.firstName?.default,d.lastName?.default].filter(Boolean).join(' ')||player.name,team:player.team||d.currentTeamAbbrev||'',position:player.position||d.position||''};$('statsSelected').textContent=`Selected: ${playerSelections.stats.name}${playerSelections.stats.team?' · '+playerSelections.stats.team:''}`;status('playerStatus',`${playerSelections.stats.name} · Career totals`,'success');$('playerProfile').innerHTML=d.headshot?`<img src="${esc(d.headshot)}" alt="${esc(playerSelections.stats.name)}" style="width:72px;height:72px;border-radius:50%;object-fit:cover;margin:12px 0">`:'';$('playerStats').innerHTML=metricRows(career).map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>Career ${esc(x[0].toLowerCase())}</span></div>`).join('')||'<div class="empty">No career totals were returned.</div>';const seasons=(d.seasonTotals||[]).filter(s=>s.gameTypeId===2&&s.leagueAbbrev==='NHL').sort((a,b)=>b.season-a.season);if(seasons.length)$('seasonStats').innerHTML=seasonTable(seasons,playerSelections.stats.position==='G');else if(Object.keys(featured).length)$('seasonStats').innerHTML='<div class="description" style="padding:14px">Most recent season: '+metricRows(featured).map(x=>`${esc(x[0])} ${esc(x[1])}`).join(' · ')+'</div>'}catch(e){status('playerStatus',e.message,'error')}finally{busy(btn,false)}}
$('loadPlayerStats').addEventListener('click',()=>loadPlayerStats());

const num=x=>Number(x)||0;
async function loadHistory(player=playerSelections.history) {
 const btn=$('loadHistory'),opp=$('opponent').value;
 if(!player){status('historyStatus','Search for and select a player by name first.','error');return}
 busy(btn,true,'Loading…');$('historySummary').innerHTML='';$('historyTable').innerHTML='';
 try{
  const landing=await get(`/player/${encodeURIComponent(player.id)}/landing`);
  const seasons=[...new Set((landing.seasonTotals||[]).filter(s=>s.gameTypeId===2&&s.leagueAbbrev==='NHL').map(s=>s.season).filter(Boolean))].sort((a,b)=>b-a);
  if(!seasons.length)throw Error('No regular-season game history is available.');
  const position=String(player.position||landing.position||'').toUpperCase(),isGoalie=position==='G'||position.includes('GOALIE');
  const requested=$('sample').value,needed=requested==='all'||requested==='two-seasons'?Infinity:Number(requested),matches=[];let seasonsChecked=0,failed=0;
  const readSeason=async season=>{try{const data=await get(`/player/${encodeURIComponent(player.id)}/game-log/${season}/2`);return(data.gameLog||[]).filter(g=>g.opponentAbbrev===opp||g.opponent===opp).map(g=>({...g,season}))}catch{failed++;return[]}};
  if(Number.isFinite(needed)){for(const season of seasons){seasonsChecked++;status('historyStatus',`Checking ${String(season).replace(/(\d{4})(\d{4})/,'$1–$2')}… ${matches.length} of ${needed} games found`);matches.push(...await readSeason(season));if(matches.length>=needed)break}}
  else if(requested==='two-seasons'){const recentSeasons=seasons.slice(0,2);seasonsChecked=recentSeasons.length;status('historyStatus',`Checking the last ${recentSeasons.length} NHL seasons…`);matches.push(...(await Promise.all(recentSeasons.map(readSeason))).flat())}
  else{for(let i=0;i<seasons.length;i+=4){const batch=seasons.slice(i,i+4);seasonsChecked+=batch.length;status('historyStatus',`Checking career history… ${seasonsChecked} of ${seasons.length} seasons`);matches.push(...(await Promise.all(batch.map(readSeason))).flat())}}
  if(failed===seasonsChecked&&!matches.length)throw Error('Could not load player game logs. Check the NHL data connection and try again.');
  matches.sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''));const shown=Number.isFinite(needed)?matches.slice(0,needed):matches;
  if(!matches.length){status('historyStatus',`No games against ${teams.find(t=>t[0]===opp)?.[1]||opp} were found in available regular seasons.`);return}
  const t={gp:shown.length,g:shown.reduce((n,x)=>n+num(x.goals),0),a:shown.reduce((n,x)=>n+num(x.assists),0),p:shown.reduce((n,x)=>n+num(x.points),0),s:shown.reduce((n,x)=>n+num(x.shots),0)};
  status('historyStatus',`${player.name} vs ${teams.find(x=>x[0]===opp)?.[1]||opp} · ${shown.length} games found across ${seasonsChecked} season${seasonsChecked===1?'':'s'}`,'success');
  if(isGoalie){
   const decisions=shown.map(g=>String(g.decision||g.result||'').toUpperCase()),wins=decisions.filter(x=>x==='W'||x==='WIN').length,losses=decisions.filter(x=>x==='L'||x==='LOSS').length,otLosses=decisions.filter(x=>x==='O'||x==='OT'||x==='OTL').length;
   const minutes=g=>{const bits=String(g.toi||'').split(':').map(Number);return bits.length===2&&bits.every(Number.isFinite)?bits[0]+bits[1]/60:bits.length===3&&bits.every(Number.isFinite)?bits[0]*60+bits[1]+bits[2]/60:0};
   const totalMinutes=shown.reduce((n,g)=>n+minutes(g),0),ga=shown.reduce((n,g)=>n+num(g.goalsAgainst),0),shotsAgainst=shown.reduce((n,g)=>n+num(g.shotsAgainst),0),saves=shown.reduce((n,g)=>n+(g.saves==null?Math.max(0,num(g.shotsAgainst)-num(g.goalsAgainst)):num(g.saves)),0),savePct=shotsAgainst?saves/shotsAgainst:null,gaa=totalMinutes?ga*60/totalMinutes:null;
   $('historySummary').innerHTML=[['Record',`${wins}–${losses}–${otLosses}`],['Games',shown.length],['Goals against',ga],['Goals-against average',gaa===null?'—':gaa.toFixed(2)],['Save percentage',savePct===null?'—':savePct.toFixed(3)],['Saves',saves],['Shots against',shotsAgainst]].map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>${esc(x[0])}</span></div>`).join('');
   $('historyTable').innerHTML='<table><thead><tr><th>Date</th><th>Season</th><th>Opponent</th><th>Decision</th><th>Saves</th><th>Shots against</th><th>Goals against</th><th>SV%</th><th>TOI</th></tr></thead><tbody>'+shown.map(g=>{const faced=num(g.shotsAgainst),against=num(g.goalsAgainst),sv=g.saves==null?Math.max(0,faced-against):num(g.saves),pct=faced?sv/faced:g.savePctg;return `<tr><td>${esc(g.gameDate||'—')}</td><td>${esc(String(g.season).replace(/(\d{4})(\d{4})/,'$1–$2'))}</td><td>${esc(g.opponentAbbrev||opp)}</td><td>${esc(g.decision||g.result||'—')}</td><td>${g.saves==null?sv:g.saves}</td><td>${g.shotsAgainst??'—'}</td><td>${g.goalsAgainst??'—'}</td><td>${pct==null?'—':Number(pct).toFixed(3)}</td><td>${esc(g.toi||'—')}</td></tr>`}).join('')+'</tbody></table>';
  }else{
   const pointPct=Math.round(100*shown.filter(g=>num(g.points)>0).length/shown.length);
   $('historySummary').innerHTML=[['Games',t.gp],['Goals',t.g],['Assists',t.a],['Points',t.p],['Shots',t.s],['Shots / game',(t.s/t.gp).toFixed(2)],['Games with a point',pointPct+'%']].map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>${esc(x[0])}</span></div>`).join('');
   $('historyTable').innerHTML='<table><thead><tr><th>Date</th><th>Season</th><th>Opponent</th><th>Goals</th><th>Assists</th><th>Points</th><th>Shots</th><th>TOI</th></tr></thead><tbody>'+shown.map(g=>`<tr><td>${esc(g.gameDate||'—')}</td><td>${esc(String(g.season).replace(/(\d{4})(\d{4})/,'$1–$2'))}</td><td>${esc(g.opponentAbbrev||opp)}</td><td>${num(g.goals)}</td><td>${num(g.assists)}</td><td>${num(g.points)}</td><td>${num(g.shots)}</td><td>${esc(g.toi||'—')}</td></tr>`).join('')+'</tbody></table>';
  }
 }catch(e){status('historyStatus',e.message,'error')}finally{busy(btn,false)}
}
$('loadHistory').addEventListener('click',()=>loadHistory());
$('savePlayer').addEventListener('click',()=>{const p=playerSelections.history;if(!p){status('historyStatus','Select a player by name before saving.','error');return}try{const saved=readSaved().filter(x=>String(x.id)!==String(p.id));saved.push({id:String(p.id),name:p.name,team:p.team});localStorage.setItem('pp_players',JSON.stringify(saved));status('historyStatus',`${p.name} saved on this device.`,'success')}catch{status('historyStatus','Browser storage is unavailable.','error')}});

let teamRows=[],activeDirectoryTeam='';
const recentFormCache=new Map();
function nhlSeasonIds(){const now=new Date(),year=now.getFullYear(),start=now.getMonth()>=6?year:year-1;return [Number(`${start}${start+1}`),Number(`${start-1}${start}`)]}
function formBadge(form){if(!form)return '';const reasons=[];if(form.points>=10)reasons.push(`${form.points} points in the last 10 games`);if(form.shotStreak>=5)reasons.push(`${form.shotStreak} straight games with a shot on goal`);return reasons.length?`<span class="hot-badge" role="img" aria-label="Hot: ${esc(reasons.join('; '))}" title="${esc(reasons.join(' · '))}">🔥</span>`:''}
async function recentPlayerForm(player){
 const [current,previous]=nhlSeasonIds(),key=`${player.id}:${current}`;
 if(recentFormCache.has(key))return recentFormCache.get(key);
 const request=(async()=>{
  try{
   const first=await get(`/player/${encodeURIComponent(player.id)}/game-log/${current}/2`),games=[...(first.gameLog||[])];
   if(games.length<10){const prior=await get(`/player/${encodeURIComponent(player.id)}/game-log/${previous}/2`);games.push(...(prior.gameLog||[]))}
   games.sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''));const last=games.slice(0,10);
   if(!last.length)return null;
   const points=last.reduce((sum,g)=>sum+num(g.points),0);let shotStreak=0;
   for(const game of games){if(num(game.shots)<1)break;shotStreak++}
   return {points,shotStreak};
  }catch{return {unavailable:true}}
 })();recentFormCache.set(key,request);return request;
}
function teamLogo(ab){return `https://assets.nhle.com/logos/nhl/svg/${encodeURIComponent(ab)}_light.svg`}
async function loadTeamDefense(ab,season){
 const statusNode=$('teamDefenseStatus'),tableNode=$('teamDefenseTable');if(!statusNode||!tableNode)return;
 statusNode.textContent='Calculating season-to-date defense splits…';tableNode.innerHTML='';
 try{
  const data=await get(`/api/team-defense/${encodeURIComponent(ab)}/${season}`,45000);
  if(activeDirectoryTeam!==ab)return;
  const seasonLabel=String(data.season).replace(/(\d{4})(\d{4})/,'$1–$2');
  if(!data.gamesProcessed){statusNode.textContent=data.gamesScheduled?'Game details could not be loaded yet. Please try again shortly.':`No completed regular-season games for ${seasonLabel} yet.`;return}
  statusNode.textContent=`${data.team} · ${seasonLabel} · ${data.gamesProcessed} team games${data.failed?` · ${data.failed} game details unavailable`:''}`;
  const positions=[['Forwards',data.allowed.Forwards],['Defensemen',data.allowed.Defensemen],['Goalies',data.allowed.Goalies]];
  tableNode.innerHTML='<table><thead><tr><th>Opponent position</th><th>Shots allowed</th><th>SOG / game</th><th>Goals allowed</th><th>Goals / game</th><th>Points allowed</th><th>PTS / game</th></tr></thead><tbody>'+positions.map(([name,stats])=>`<tr><td><b>${name}</b></td><td>${stats.shots}</td><td>${(stats.shots/data.gamesProcessed).toFixed(1)}</td><td>${stats.goals||0}</td><td>${((stats.goals||0)/data.gamesProcessed).toFixed(2)}</td><td>${stats.points}</td><td>${(stats.points/data.gamesProcessed).toFixed(2)}</td></tr>`).join('')+'</tbody></table>';
 }catch(e){if(activeDirectoryTeam===ab)statusNode.textContent=e.message}
}
function renderTeamDirectory(){const q=$('teamDirectorySearch').value.trim().toLowerCase();$('teamDirectoryGrid').innerHTML=teams.filter(t=>`${t[0]} ${t[1]}`.toLowerCase().includes(q)).map(t=>{const record=teamRows.find(r=>(r.teamAbbrev?.default||r.teamAbbrev)===t[0]);return `<button class="directory-card" data-team="${t[0]}"><span class="directory-code">${t[0]}</span><span><b>${esc(t[1])}</b><small>${record?`${record.wins||0}–${record.losses||0}–${record.otLosses||0} · ${record.points||0} pts`:'Open team directory'}</small></span></button>`}).join('');document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>loadTeamRoster(b.dataset.team)))}
$('teamDirectorySearch').addEventListener('input',renderTeamDirectory);
async function loadTeamRoster(ab){
 activeDirectoryTeam=ab;$('directoryRoster').innerHTML='';status('directoryStatus',`Loading ${teams.find(t=>t[0]===ab)?.[1]||ab} roster…`);
 try{
  const d=await get(`/roster/${encodeURIComponent(ab)}/current`),groups=[['Forwards',d.forwards||[]],['Defense',d.defensemen||d.defense||[]],['Goalies',d.goalies||[]]],total=groups.reduce((n,g)=>n+g[1].length,0);
  if(!total)throw Error('No roster was returned for this team.');
  const players=groups.flatMap(g=>g[1]).map(p=>({id:String(p.id??p.playerId),name:[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||p.name||'Player',team:ab,position:p.positionCode||'',headshot:p.headshot||'',sweaterNumber:p.sweaterNumber}));
  status('directoryStatus',`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · Checking recent form…`);
  $('directoryRoster').innerHTML=`<div class="panelhead" style="margin-top:22px"><div><h3>${esc(teams.find(t=>t[0]===ab)?.[1]||ab)}</h3><p>Choose a player to open their stats or matchup history.</p></div><button class="btn" id="closeRoster">Close directory</button></div><p class="form-legend">🔥 10+ points in the last 10 NHL games · 5+ consecutive games with a shot on goal</p>`+groups.filter(g=>g[1].length).map(([label,rawPlayers])=>`<div class="roster-group"><h4>${label} · ${rawPlayers.length}</h4><div class="roster-grid">${rawPlayers.map(p=>{const player=players.find(x=>x.id===String(p.id??p.playerId));return `<div class="roster-player">${player.headshot?`<img src="${esc(player.headshot)}" alt="" loading="lazy">`:''}<span class="grow"><span class="roster-name"><b>${esc(player.name)}</b><span class="form-marker" data-form-player="${esc(player.id)}" aria-live="polite"><span class="form-pending">checking</span></span></span><small>${player.position?esc(player.position)+' · ':''}${player.sweaterNumber?`#${esc(player.sweaterNumber)}`:''}</small></span><button class="btn" data-roster-stats="${esc(player.id)}">Stats</button><button class="btn" data-roster-history="${esc(player.id)}">Matchup</button></div>`}).join('')}</div></div>`).join('')+`<section class="defense-panel"><div class="panelhead"><div><h4>Defense vs. opponent position</h4><p>Season-to-date totals and per-game rates for players facing this club.</p></div><span class="pill">${String(nhlSeasonIds()[0]).replace(/(\d{4})(\d{4})/,'$1–$2')}</span></div><div id="teamDefenseStatus" class="status" role="status">Loading position splits…</div><div id="teamDefenseTable" class="tablewrap"></div></section>`;
  $('closeRoster').addEventListener('click',()=>{$('directoryRoster').innerHTML='';status('directoryStatus','Choose a club to open its roster.')});
  players.forEach(p=>{document.querySelector(`[data-roster-stats="${CSS.escape(p.id)}"]`)?.addEventListener('click',()=>openPlayer(p,'stats'));document.querySelector(`[data-roster-history="${CSS.escape(p.id)}"]`)?.addEventListener('click',()=>openPlayer(p,'history'))});
  loadTeamDefense(ab,nhlSeasonIds()[0]);
  const skaters=players.filter(p=>p.position!=='G'),hotCount={value:0},failedCount={value:0};let done=0,next=0;
  const worker=async()=>{while(next<skaters.length){const player=skaters[next++],form=await recentPlayerForm(player);done++;const marker=document.querySelector(`[data-form-player="${CSS.escape(player.id)}"]`);if(marker&&activeDirectoryTeam===ab){if(form?.unavailable){failedCount.value++;marker.innerHTML='<span class="form-pending" title="Recent form could not be loaded">—</span>'}else{marker.innerHTML=formBadge(form);if(marker.innerHTML)hotCount.value++}status('directoryStatus',`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · Checking recent form ${done}/${skaters.length}…`)}}};
  await Promise.all(Array.from({length:Math.min(8,skaters.length)},worker));
  if(activeDirectoryTeam===ab)status('directoryStatus',failedCount.value===skaters.length&&skaters.length?`Roster loaded · Recent form is unavailable right now.`:`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · ${hotCount.value?`${hotCount.value} player${hotCount.value===1?'':'s'} trending 🔥`:'Recent form checked'}`,failedCount.value===skaters.length?'':'success');
 }catch(e){if(activeDirectoryTeam===ab)status('directoryStatus',e.message,'error')}
}
function openPlayer(p,view){selectPlayer(view,p);document.querySelector(`[data-tab="${view==='stats'?'player':'history'}"]`).click();if(view==='stats')loadPlayerStats(p);else $('historyPlayerSearch').focus()}

async function loadTeams(){const btn=$('loadTeams');busy(btn,true,'Loading…');status('teamStatus','Loading team stats…');try{const d=await get('/standings/now');teamRows=d.standings||[];if(!teamRows.length)throw Error('No team statistics were returned.');drawTeams();renderTeamDirectory();status('teamStatus',`${teamRows.length} teams · standings updated ${d.standingsDate||'today'}`,'success')}catch(e){status('teamStatus',e.message,'error')}finally{busy(btn,false)}}
function drawTeams(){const q=$('teamFilter').value.trim().toLowerCase(),rows=teamRows.filter(t=>`${t.teamName?.default||''} ${t.teamAbbrev?.default||t.teamAbbrev||''} ${t.divisionName||''} ${t.conferenceName||''}`.toLowerCase().includes(q));$('teamsTable').innerHTML=rows.length?'<table><thead><tr><th>Team</th><th>Division</th><th>GP</th><th>W</th><th>L</th><th>OT</th><th>PTS</th><th>Points %</th><th>GF</th><th>GA</th><th>DIFF</th></tr></thead><tbody>'+rows.map(t=>{const ab=t.teamAbbrev?.default||t.teamAbbrev||'';return `<tr><td><b>${esc(t.teamName?.default||ab)}</b></td><td>${esc(t.divisionName||'—')}</td><td>${esc(t.gamesPlayed??'—')}</td><td>${esc(t.wins??'—')}</td><td>${esc(t.losses??'—')}</td><td>${esc(t.otLosses??'—')}</td><td><b>${esc(t.points??'—')}</b></td><td>${t.pointPctg!=null?`${(100*t.pointPctg).toFixed(1)}%`:'—'}</td><td>${esc(t.goalFor??'—')}</td><td>${esc(t.goalAgainst??'—')}</td><td>${esc(t.goalDifferential??'—')}</td></tr>`}).join('')+'</tbody></table>':'<div class="empty">No team records found.</div>'}
$('loadTeams').addEventListener('click',loadTeams);$('teamFilter').addEventListener('input',drawTeams);

function readSaved(){try{const v=JSON.parse(localStorage.getItem('pp_players')||'[]');return Array.isArray(v)?v.filter(p=>p&&/^\d+$/.test(String(p.id))):[]}catch{return[]}}
function renderSaved(){const saved=readSaved();$('savedList').innerHTML=saved.length?saved.map((p,i)=>`<div class="savedrow"><div><b>${esc(p.name||'Player')}</b>${p.team?`<div class="description">${esc(p.team)}</div>`:''}</div><div class="savedactions"><button class="btn" data-open="${i}">Open matchup</button><button class="btn" data-stats="${i}">Player stats</button><button class="btn" data-remove="${i}">Remove</button></div></div>`).join(''):'<div class="empty">No saved players yet. Save a player from matchup history to keep them here.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openPlayer(saved[+b.dataset.open],'history')));document.querySelectorAll('[data-stats]').forEach(b=>b.addEventListener('click',()=>openPlayer(saved[+b.dataset.stats],'stats')));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('pp_players',JSON.stringify(saved.filter((_,i)=>i!==+b.dataset.remove)));renderSaved()}))}

function seasonIdsForDate(date){const d=new Date(`${date}T12:00:00`),year=d.getFullYear(),start=d.getMonth()>=6?year:year-1;return [Number(`${start}${start+1}`),Number(`${start-1}${start}`)]}
function hitRate(games,key,threshold){return games.length?games.filter(g=>num(g[key])>=threshold).length/games.length:null}
function weightedRate(parts){const usable=parts.filter(x=>x.rate!=null&&x.weight>0);return usable.length?usable.reduce((n,x)=>n+x.rate*x.weight,0)/usable.reduce((n,x)=>n+x.weight,0):0}
function pickPropLabel(key,threshold){return key==='points'?'1+ point':key==='shots'?`${threshold}+ shots on goal`:'1+ goal'}
let activePickType='shots',pickLists={shots:[],points:[],goals:[]},pickDefense={};
function renderPickCards(){const picks=pickLists[activePickType]||{},defense=pickDefense;$('picksOut').innerHTML=picks.length?picks.map((p,i)=>{const oppSplit=defense[p.opp],posKey=p.position==='D'?'Defensemen':'Forwards',split=oppSplit?.allowed?.[posKey],allowedKey=p.prop.key==='goals'?'goals':p.prop.key==='points'?'points':'shots',rate=split&&oppSplit.gamesProcessed?split[allowedKey]/oppSplit.gamesProcessed:null;return `<article class="pick-card"><span class="pick-rank">#${i+1}</span><h4>${esc(p.name)}</h4><div class="pick-meta">${esc(p.team)} · ${esc(p.position==='D'?'Defense':'Forward')} vs ${esc(p.opp)}</div><div class="pick-prop">${esc(pickPropLabel(p.prop.key,p.prop.threshold))}</div><div class="pick-rate">${Math.round(p.rate*100)}% empirical estimate</div><div class="pick-detail">Recent 10: ${p.recentHits}/${p.recent.length||'—'} · This season: ${p.currentHits}/${p.current.length||'—'} · Previous: ${p.priorHits}/${p.prior.length||'—'}</div><div class="pick-detail">Vs opponent, last 2 seasons: ${p.h2h.length?`${p.h2hHits}/${p.h2h.length}`:'no games in sample'}${rate!=null?` · Opponent allows ${rate.toFixed(2)} ${allowedKey} per ${posKey.toLowerCase()} player/game (${oppSplit.gamesProcessed} team games)`:''}</div>${p.recent.length<5?'<div class="pick-detail pick-warn">Limited recent sample</div>':''}</article>`}).join(''):'<div class="empty">No qualified player trends are available for this prop and slate yet.</div>'}
document.querySelectorAll('[data-pick-view]').forEach(button=>button.addEventListener('click',()=>{activePickType=button.dataset.pickView;document.querySelectorAll('[data-pick-view]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-selected',String(x===button))});renderPickCards()}));
async function buildDailyPicks(){const btn=$('buildPicks'),date=$('picksDate').value;busy(btn,true,'Researching…');pickLists={shots:[],points:[],goals:[]};pickDefense={};renderPickCards();status('picksStatus','Loading the slate…');try{
 const slateData=await get(`/score/${encodeURIComponent(date)}`),games=(slateData.games||[]).filter(g=>!['OFF','FINAL'].includes(g.gameState));if(!games.length){status('picksStatus','No upcoming games are scheduled for this date. Select a slate with games that have not started.');return}
 const teamsPlaying=[...new Set(games.flatMap(g=>[g.homeTeam?.abbrev,g.awayTeam?.abbrev]).filter(Boolean))],seasonIds=seasonIdsForDate(date),rosters=await Promise.all(teamsPlaying.map(async ab=>{try{const d=await get(`/roster/${encodeURIComponent(ab)}/current`);return {ab,players:[...(d.forwards||[]),...(d.defensemen||d.defense||[])].map(p=>({id:String(p.id??p.playerId),name:[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||p.name||'Player',team:ab,position:p.positionCode||'',headshot:p.headshot||''})).filter(p=>p.id&&p.id!=='undefined')}}catch{return {ab,players:[]}}}));
 const players=[...new Map(rosters.flatMap(x=>x.players).map(p=>[p.id,p])).values()];if(!players.length)throw Error('Could not load skater rosters for this slate.');status('picksStatus',`Comparing ${players.length} skaters across ${games.length} games · loading two seasons of game logs…`);
 const logData=new Map();let next=0,finished=0;const worker=async()=>{while(next<players.length){const player=players[next++];const logs=await Promise.all(seasonIds.map(async season=>{try{return(await get(`/player/${encodeURIComponent(player.id)}/game-log/${season}/2`)).gameLog||[]}catch{return []}}));logData.set(player.id,logs.map(list=>list.filter(g=>(g.gameDate||'')<date).sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''))));finished++;if(finished%12===0||finished===players.length)status('picksStatus',`Comparing ${players.length} skaters · game logs ${finished}/${players.length}…`)} };await Promise.all(Array.from({length:Math.min(12,players.length)},worker));
  const candidates=[];for(const game of games){const home=game.homeTeam?.abbrev,away=game.awayTeam?.abbrev;for(const player of players.filter(p=>p.team===home||p.team===away)){const opp=player.team===home?away:home,[currentAll,prior]=logData.get(player.id)||[[],[]],current=currentAll.slice(0,1000),recent=[...current,...prior].sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10),h2h=[...currentAll,...prior].filter(g=>g.opponentAbbrev===opp||g.opponent===opp).sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10);if(recent.length<3)continue;const props=[{key:'points',threshold:1},{key:'shots',threshold:2},{key:'shots',threshold:3},{key:'goals',threshold:1}];for(const prop of props){const r=hitRate(recent,prop.key,prop.threshold),c=hitRate(current,prop.key,prop.threshold),p=hitRate(prior,prop.key,prop.threshold),h=hitRate(h2h,prop.key,prop.threshold),rate=weightedRate([{rate:r,weight:.50},{rate:c,weight:.30},{rate:p,weight:.20}]);const evidence=[recent.length,current.length,prior.length].reduce((a,n)=>a+n,0);if(evidence<6)continue;candidates.push({name:player.name,team:player.team,position:player.position,opp,prop,rate,recent,current,prior,h2h,recentHits:recent.filter(g=>num(g[prop.key])>=prop.threshold).length,currentHits:current.filter(g=>num(g[prop.key])>=prop.threshold).length,priorHits:prior.filter(g=>num(g[prop.key])>=prop.threshold).length,h2hHits:h2h.filter(g=>num(g[prop.key])>=prop.threshold).length,evidence})}}}
 const bestFor=key=>{const best=new Map();for(const p of candidates.filter(x=>x.prop.key===key).sort((a,b)=>b.rate-a.rate||b.evidence-a.evidence)){const k=p.name+':'+p.team;if(!best.has(k))best.set(k,p)}return [...best.values()].slice(0,10)};pickLists={shots:bestFor('shots'),points:bestFor('points'),goals:bestFor('goals')};const allTop=[...pickLists.shots,...pickLists.points,...pickLists.goals];if(!allTop.length){status('picksStatus','There is not enough regular-season player history yet to form top 10 lists for this slate.');return}renderPickCards();status('picksStatus',`Built separate SOG, points, and goals lists from ${players.length} skaters · estimates weight last 10 games 50%, this season 30%, previous season 20%. Loading opponent position splits…`,'success');
 const opponents=[...new Set(allTop.map(p=>p.opp))];let dn=0;await Promise.all(opponents.map(async opp=>{try{pickDefense[opp]=await get(`/api/team-defense/${encodeURIComponent(opp)}/${seasonIds[0]}`,45000)}catch{}dn++;status('picksStatus',`Top 10 lists ready · opponent position splits ${dn}/${opponents.length}…`)}));renderPickCards();status('picksStatus',`Top 10 lists ready · ${players.length} skaters analyzed · SOG, points, and goals projections show separate history and sample counts. Defense splits use completed games in the selected season.`,'success');
 }catch(e){status('picksStatus',e.message,'error')}finally{busy(btn,false)}}
$('picksDate').value=dateStr(new Date());$('buildPicks').addEventListener('click',buildDailyPicks);
renderTeamDirectory();loadScores();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
