'use strict';

const teams=[['ANA','Anaheim Ducks'],['BOS','Boston Bruins'],['BUF','Buffalo Sabres'],['CGY','Calgary Flames'],['CAR','Carolina Hurricanes'],['CHI','Chicago Blackhawks'],['COL','Colorado Avalanche'],['CBJ','Columbus Blue Jackets'],['DAL','Dallas Stars'],['DET','Detroit Red Wings'],['EDM','Edmonton Oilers'],['FLA','Florida Panthers'],['LAK','Los Angeles Kings'],['MIN','Minnesota Wild'],['MTL','Montreal Canadiens'],['NSH','Nashville Predators'],['NJD','New Jersey Devils'],['NYI','New York Islanders'],['NYR','New York Rangers'],['OTT','Ottawa Senators'],['PHI','Philadelphia Flyers'],['PIT','Pittsburgh Penguins'],['SJS','San Jose Sharks'],['SEA','Seattle Kraken'],['STL','St. Louis Blues'],['TBL','Tampa Bay Lightning'],['TOR','Toronto Maple Leafs'],['UTA','Utah Mammoth'],['VAN','Vancouver Canucks'],['VGK','Vegas Golden Knights'],['WSH','Washington Capitals'],['WPG','Winnipeg Jets']];
const $=id=>document.getElementById(id),proxyServer=location.protocol.startsWith('http'),api=proxyServer?'/api/nhl/v1':'https://api-web.nhle.com/v1',searchApi=proxyServer?'/api/player-search':'https://search.d3.nhle.com/api/v1/search/player',cache=new Map(),playerSelections={stats:null,history:null};
const dateStr=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
$('scoreDate').value=dateStr(new Date());$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date());
$('opponent').innerHTML=teams.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function status(id,msg,type=''){const el=$(id);el.textContent=msg;const pending=!type&&/\b(loading|fetching|searching|checking|calculating|comparing|researching|building|processing)\b/i.test(msg);el.className='status'+(type?' '+type:'')+(pending?' is-loading':'')}
async function fetchJson(url,timeout=4500){const response=await fetch(url,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(timeout)});if(!response.ok){let detail='';try{const body=await response.json();detail=body.error||body.message||''}catch{}throw Error(detail||`Request failed (HTTP ${response.status})`)}return response.json()}
async function get(path,timeout=proxyServer?10000:3500){const url=path.startsWith('http')?path:proxyServer&&path.startsWith('/api/')?path:api+path;if(cache.has(url))return cache.get(url);const request=(async()=>{try{return await fetchJson(url,timeout)}catch(localError){if(proxyServer){const directNhl=url.startsWith('/api/nhl/v1/')?'https://api-web.nhle.com/v1'+url.slice('/api/nhl/v1'.length):'';if(!directNhl)throw localError;try{return await fetchJson(directNhl,3500)}catch{}const relays=['https://api.codetabs.com/v1/proxy?quest='+encodeURIComponent(directNhl),'https://api.allorigins.win/raw?url='+encodeURIComponent(directNhl)];try{return await Promise.any(relays.map(relay=>fetchJson(relay,4500)))}catch{if(localError.name==='TimeoutError')throw Error('The local NHL server and direct data feed both timed out.');if(localError instanceof TypeError)throw Error('Cannot reach the local Puck Props server or NHL data feed. Check that the server is running and your internet connection is available.');throw Error('Could not load NHL data from the local server or its fallback feeds.')}}const relays=['https://api.codetabs.com/v1/proxy?quest='+encodeURIComponent(url),'https://api.allorigins.win/raw?url='+encodeURIComponent(url)];try{return await Promise.any(relays.map(relay=>fetchJson(relay,4500)))}catch{throw Error('The NHL data service could not be reached. For reliable local access, launch the app with start.bat or run node server.js.')}}})();cache.set(url,request);try{return await request}catch(e){cache.delete(url);throw e}}
function busy(btn,on,label){if(on){if(!btn.disabled)btn.dataset.label=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.label||btn.textContent;btn.disabled=false}}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab!=='teams'&&$('player').classList.contains('team-player-detail'))restoreTeamPlayerSections();document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);if(x===b)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});['scores','picks','bets','history','teams','player'].forEach(id=>$(id).classList.toggle('hidden',id!==b.dataset.tab));if(b.dataset.tab==='teams'){renderTeamDirectory();if(!teamRows.length)loadTeams();else drawTeams()}}));

function teamMatchupMarkers(games){const byAb=new Map(teamRows.map(t=>[t.teamAbbrev?.default||t.teamAbbrev,t])),out={};for(const g of games){const away=byAb.get(g.awayTeam?.abbrev),home=byAb.get(g.homeTeam?.abbrev);if(!away||!home||num(away.gamesPlayed)<5||num(home.gamesPlayed)<5)continue;const rate=t=>({gf:num(t.goalFor)/num(t.gamesPlayed),ga:num(t.goalAgainst)/num(t.gamesPlayed)}),a=rate(away),h=rate(home),margin=((h.gf+a.ga)-(a.gf+h.ga))/2,homeWin=1/(1+Math.exp(-margin/1.45)),fav=margin>=0?'home':'away',favProb=fav==='home'?homeWin:1-homeWin,cover=1/(1+Math.exp(-(Math.abs(margin)-1.5)/1.15));out[g.id]={away:1-homeWin,home:homeWin,fav,favProb,cover}}return out}
const teamLast10Cache=new Map();
let scoreboardGames=[];
let goalieReportDate='',goalieReportPromise=null,goalieReportData=null;
async function getGoalieReports(date){if(goalieReportDate===date&&goalieReportData)return goalieReportData;if(goalieReportPromise)return goalieReportPromise;goalieReportPromise=(async()=>{try{const data=await fetchJson(`/api/starting-goalies/${encodeURIComponent(date)}`,14000);goalieReportDate=date;goalieReportData=data;return data}finally{goalieReportPromise=null}})();return goalieReportPromise}
async function updateScoreboardGoalies(games,date){try{const data=await getGoalieReports(date);if($('scoreDate').value!==date)return;for(const game of games){const row=document.querySelector(`[data-goalie-game="${CSS.escape(String(game.id))}"]`);if(!row)continue;const away=data.goalies?.[game.awayTeam?.abbrev],home=data.goalies?.[game.homeTeam?.abbrev],format=(team,goalie)=>`${team?.abbrev||'Team'}: ${goalie?.name||'Not reported'}${goalie?` · ${goalie.status}`:''}`;row.textContent=`Goalies · ${format(game.awayTeam,away)}  |  ${format(game.homeTeam,home)}`;row.title=`Starter reports from ${data.source||'Daily Faceoff'}; check again before puck drop.`}}catch{if($('scoreDate').value!==date)return;document.querySelectorAll('[data-goalie-game]').forEach(row=>{row.textContent='Goalie reports unavailable · open matchup details to retry'})}}
async function loadTeamLast10(team,slateDate){const key=`${team}:${slateDate}`;if(teamLast10Cache.has(key))return teamLast10Cache.get(key);const request=(async()=>{const seasons=seasonIdsForDate(slateDate),schedules=await Promise.all(seasons.map(async season=>{try{return(await get(`/club-schedule-season/${encodeURIComponent(team)}/${season}`)).games||[]}catch{return []}})),games=[...new Map(schedules.flat().filter(g=>g.gameType===2&&['OFF','FINAL'].includes(g.gameState)&&(g.gameDate||'')<slateDate).map(g=>[String(g.id),g])).values()].sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')),last=games.slice(0,10);if(!last.length)return null;let w=0,l=0,otl=0;for(const g of last){const home=g.homeTeam?.abbrev===team,teamScore=Number(home?g.homeTeam?.score??g.homeScore:g.awayTeam?.score??g.awayScore),oppScore=Number(home?g.awayTeam?.score??g.awayScore:g.homeTeam?.score??g.homeScore);if(!Number.isFinite(teamScore)||!Number.isFinite(oppScore))continue;if(teamScore>oppScore)w++;else if(/OT|SO/i.test(`${g.gameOutcome?.lastPeriodType||''} ${g.periodDescriptor?.periodType||''}`))otl++;else l++}return {w,l,otl,gp:last.length}})();teamLast10Cache.set(key,request);try{return await request}catch{teamLast10Cache.delete(key);return null}}
async function updateScoreboardLast10(){const date=$('scoreDate').value;try{const {games=[]}=await get(`/score/${encodeURIComponent(date)}`),clubs=[...new Set(games.flatMap(g=>[g.awayTeam?.abbrev,g.homeTeam?.abbrev]).filter(Boolean))],records=Object.fromEntries(await Promise.all(clubs.map(async team=>[team,await loadTeamLast10(team,date)])));if($('scoreDate').value!==date)return;for(const game of games){let card=document.querySelector(`[data-game-id="${CSS.escape(String(game.id))}"]`);for(let tries=0;!card&&tries<25;tries++){await new Promise(resolve=>setTimeout(resolve,100));card=document.querySelector(`[data-game-id="${CSS.escape(String(game.id))}"]`)}if(!card)continue;const lines=card.querySelectorAll('.teamline .teamname');for(const [index,team] of [[0,game.awayTeam?.abbrev],[1,game.homeTeam?.abbrev]]){const line=lines[index],r=records[team];if(!line||!r||line.querySelector('.team-last10'))continue;const badge=document.createElement('small');badge.className='team-last10';badge.textContent=`L10 ${r.w}-${r.l}-${r.otl}`;badge.title=`Last ${r.gp} completed regular-season games before ${date}`;line.append(badge)}}}catch{}}
let scoreRequest=0;
async function loadScores(){const btn=$('loadScores'),date=$('scoreDate').value,requestId=++scoreRequest;cache.delete(api+'/score/'+encodeURIComponent(date));cache.delete(api+'/standings/now');busy(btn,true,'Loading…');status('scoreStatus','Fetching schedule…');$('scoresOut').innerHTML='';$('boxscoreOut').innerHTML='';try{const [d]=await Promise.all([get('/score/'+encodeURIComponent(date))]);const games=d.games||[];let standingsRows;try{standingsRows=(await get('/standings/now')).standings||[]}catch{}if(requestId!==scoreRequest)return;if(standingsRows)teamRows=standingsRows;scoreboardGames=games;const markers=teamMatchupMarkers(games);status('scoreStatus',games.length?`${games.length} games scheduled · Select any matchup for details`:'No games listed for this date.',games.length?'success':'');$('scoresOut').innerHTML=games.map(g=>{const state=g.gameState==='LIVE'?'LIVE':(['OFF','FINAL'].includes(g.gameState)?'FINAL':g.startTimeUTC?new Date(g.startTimeUTC).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZoneName:'short'}):'Scheduled'),m=markers[g.id],teamTag=side=>{if(!m)return '';const p=m[side],win=p>=.6?`<span class="matchup-marker" title="Estimated win probability ${Math.round(p*100)}%">👍</span>`:'',puck=m.fav===side?`<span class="matchup-marker x2" title="Most likely -1.5 winner · estimated cover chance ${Math.round(m.cover*100)}%">×2</span>`:'';return win+puck};return `<button type="button" class="game game-clickable" aria-pressed="false" data-game-id="${esc(g.id)}" aria-label="View matchup details: ${esc(g.awayTeam?.abbrev||'Away')} at ${esc(g.homeTeam?.abbrev||'Home')}"><div class="gamehead"><span>${esc(g.gameDate||'')}</span><span>${esc(state)}</span></div><div class="teamline"><div class="teamname">${g.awayTeam?.logo?`<img src="${esc(g.awayTeam.logo)}" alt="">`:''}<span>${esc(g.awayTeam?.abbrev||'Away')}</span>${teamTag('away')}</div><span class="score">${g.awayTeam?.score??'—'}</span></div><div class="teamline"><div class="teamname">${g.homeTeam?.logo?`<img src="${esc(g.homeTeam.logo)}" alt="">`:''}<span>${esc(g.homeTeam?.abbrev||'Home')}</span>${teamTag('home')}</div><span class="score">${g.homeTeam?.score??'—'}</span></div><div class="gamefoot">${esc(g.venue?.default||'Venue to be announced')}</div><div class="goalie-line" data-goalie-game="${esc(g.id)}">Probable goalies · loading report…</div><div class="game-action">View matchup details →</div></button>`}).join('');document.querySelectorAll('[data-game-id]').forEach(card=>card.addEventListener('click',()=>openMatchup(card.dataset.gameId)));updateScoreboardGoalies(games,date)}catch(e){if(requestId===scoreRequest)status('scoreStatus',e.message,'error')}finally{if(requestId===scoreRequest){busy(btn,false);$('startupLoader')?.classList.add('hidden')}}}
function goalieCard(team,record){return `<article class="pick-card"><h4>${esc(team)}</h4><div class="pick-prop">${esc(record?.name||'Not reported yet')}</div><div class="pick-detail">${record?esc(record.status):'No probable starter published'}</div></article>`}
async function openMatchup(id){const game=scoreboardGames.find(item=>String(item.id)===String(id));if(!game)return;const detail=$('matchupDetail'),board=$('scoreboardView'),teamsInGame=[game.awayTeam,game.homeTeam],date=game.gameDate||$('scoreDate').value;board.classList.add('hidden');detail.classList.remove('hidden');$('matchupHeading').innerHTML=`<div><h3>${esc(game.awayTeam?.placeName?.default||game.awayTeam?.abbrev||'Away')} ${esc(game.awayTeam?.score??'—')} · ${esc(game.homeTeam?.placeName?.default||game.homeTeam?.abbrev||'Home')} ${esc(game.homeTeam?.score??'—')}</h3><p>${esc(date)} · ${esc(game.venue?.default||'Venue to be announced')}</p></div><span class="pill">${esc(game.gameState||'Scheduled')}</span>`;$('goalieSourceLink').href=`https://www.dailyfaceoff.com/starting-goalies/${encodeURIComponent(date)}`;$('matchupGoalies').innerHTML='';status('goalieStatus','Checking Daily Faceoff starter reports…');$('backToScoreboard').onclick=()=>{detail.classList.add('hidden');board.classList.remove('hidden');$('boxscoreOut').innerHTML=''};try{const reports=await getGoalieReports(date),goalies=reports.goalies||{};$('matchupGoalies').innerHTML=teamsInGame.map(team=>goalieCard(team?.abbrev||'Team',goalies[team?.abbrev])).join('');status('goalieStatus',Object.keys(goalies).length?`Starter report for ${date} · status may change before puck drop.`:`No starter reports are posted for this date yet.`)}catch(e){$('matchupGoalies').innerHTML=teamsInGame.map(team=>goalieCard(team?.abbrev||'Team',null)).join('');status('goalieStatus',`${e.message} Check Daily Faceoff for the latest report.`,'error')}loadGameBoxscore(id)}
function boxscorePlayerTable(group,players){const goalies=group==='Goalies',list=[...(players||[])].sort((a,b)=>goalies?Number(b.starter)-Number(a.starter):(num(b.points)-num(a.points)||num(b.sog)-num(a.sog)||String(a.name?.default||'').localeCompare(String(b.name?.default||''))));if(!list.length)return '<div class="empty">No player stats available.</div>';const columns=goalies?['Player','Decision','Saves','Shots against','SV%','GA','TOI']:['Player','G','A','PTS','SOG','+/-','TOI'];return `<h5>${group}</h5><div class="tablewrap"><table><thead><tr>${columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${list.map(p=>{const pct=p.savePctg==null?'—':Number(p.savePctg).toFixed(3),cells=goalies?[p.name?.default||'Goalie',p.decision||'—',p.saves??'—',p.shotsAgainst??'—',pct,p.goalsAgainst??'—',p.toi||'—']:[p.name?.default||'Player',p.goals??0,p.assists??0,p.points??0,p.sog??0,p.plusMinus??0,p.toi||'—'];return `<tr>${cells.map((value,i)=>`<td>${i===0?`<b>${esc(value)}</b>`:esc(value)}</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`}
async function loadGameBoxscore(id){const out=$('boxscoreOut');out.innerHTML='<div class="panel"><div class="status is-loading" role="status">Loading game player stats…</div></div>';try{const d=await get(`/gamecenter/${encodeURIComponent(id)}/boxscore`,20000),stats=d.playerByGameStats||{},sides=[['awayTeam',d.awayTeam],['homeTeam',d.homeTeam]];out.innerHTML=`<div class="panel" id="boxscorePanel"><div class="panelhead"><div><h3>Player box score</h3><p>${esc(d.venue?.default||'Game box score')} · ${esc(d.gameDate||'')}</p></div></div><div class="cards">${sides.map(([side,team])=>{const playerGroups=stats[side]||{};return `<section class="game"><h4>${esc(team?.abbrev||side)}</h4>${boxscorePlayerTable('Forwards',playerGroups.forwards)}${boxscorePlayerTable('Defense',playerGroups.defense)}${boxscorePlayerTable('Goalies',playerGroups.goalies)}</section>`}).join('')}</div></div>`}catch(e){out.innerHTML=`<div class="panel"><div class="panelhead"><div><h3>Player box score</h3><p>${esc(e.message)}</p></div></div></div>`}}
$('loadScores').addEventListener('click',loadScores);$('scoreDate').addEventListener('change',loadScores);
$('loadScores').addEventListener('click',updateScoreboardLast10);$('scoreDate').addEventListener('change',updateScoreboardLast10);

function playerName(p){return p.name||p.fullName||[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||'NHL Player'}
function normalizePlayers(data){const items=Array.isArray(data)?data:(data?.players||data?.results||data?.suggestions||[]);return items.map(p=>({id:String(p.playerId??p.id??p.player_id??''),name:playerName(p),team:p.teamAbbrev||p.team?.abbrev||p.teamName||'',position:p.positionCode||p.position||'',headshot:p.headshot||p.image||''})).filter(p=>p.id&&p.name!=='NHL Player')}
function setupSearch(inputId,resultId,slot){
 const input=$(inputId),out=$(resultId);let timer;
 input.addEventListener('input',()=>{
  clearTimeout(timer);playerSelections[slot]=null;$(`${slot}Selected`).textContent='';out.innerHTML='';
  if(slot==='stats'){$('playerProfile').innerHTML='';$('playerStats').innerHTML='';$('seasonStats').innerHTML='';status('playerStatus','Search for a player by name.');}
  const q=input.value.trim();if(q.length<3)return;
  out.innerHTML='<div class="loading-inline" role="status">Searching players…</div>';
  timer=setTimeout(async()=>{
   try{
    const url=searchApi.startsWith('/')?`${searchApi}?q=${encodeURIComponent(q)}`:searchApi+'?culture=en-us&limit=12&q='+encodeURIComponent(q),items=normalizePlayers(await get(url));
    if(!items.length){out.innerHTML='<div class="description">No matching players found.</div>';return}
    out.innerHTML=items.map((p,i)=>`<button class="player-choice" type="button" data-result="${slot}-${i}">${p.headshot?`<img src="${esc(p.headshot)}" alt="" loading="lazy">`:''}<span><b>${esc(p.name)}</b><small>${esc([p.team,p.position].filter(Boolean).join(' · ')||'NHL player')}</small></span></button>`).join('');
    items.forEach((p,i)=>$(resultId).querySelector(`[data-result="${slot}-${i}"]`).addEventListener('click',()=>{selectPlayer(slot,p);if(slot==='stats')loadPlayerStats(p)}));
    const exact=slot==='stats'?items.find(p=>p.name.trim().toLocaleLowerCase()===q.toLocaleLowerCase()):null;
    if(exact){selectPlayer(slot,exact);loadPlayerStats(exact)}
   }catch(e){out.innerHTML=`<div class="description">${esc(e.message)}</div>`}
  },250)
 });
 input.addEventListener('keydown',e=>{if(e.key==='Enter'){const first=out.querySelector('.player-choice');if(first){e.preventDefault();first.click()}}})
}
function selectPlayer(slot,p){playerSelections[slot]=p;$(slot==='stats'?'statsPlayerSearch':'historyPlayerSearch').value=p.name;$(`${slot}Selected`).textContent=`Selected: ${p.name}${p.team?' · '+p.team:''}${p.position?' · '+p.position:''}`;$(slot==='stats'?'statsPlayerResults':'historyPlayerResults').innerHTML=''}
setupSearch('statsPlayerSearch','statsPlayerResults','stats');setupSearch('historyPlayerSearch','historyPlayerResults','history');

function metricRows(c){return [['Games played',c.gamesPlayed],['Goals',c.goals],['Assists',c.assists],['Points',c.points],['Shots',c.shots],['Plus / minus',c.plusMinus],['Power-play goals',c.powerPlayGoals],['Penalty minutes',c.pim],['Wins',c.wins],['Save percentage',c.savePctg!=null?Number(c.savePctg).toFixed(3):undefined],['Goals-against average',c.goalsAgainstAvg!=null?Number(c.goalsAgainstAvg).toFixed(2):undefined],['Shutouts',c.shutouts],['Saves',c.saves]].filter(x=>x[1]!==undefined&&x[1]!==null)}
function seasonTable(seasons,isGoalie){const columns=isGoalie?['Season','Team','GP','W','L','OT','SV%','GAA','SO','Saves']:['Season','Team','GP','G','A','PTS','+/-','SOG'];const cell=(s,key)=>key==='Season'?String(s.season).replace(/(\d{4})(\d{4})/,'$1–$2'):key==='Team'?(s.teamName?.default||s.teamAbbrev||'—'):key==='GP'?(s.gamesPlayed??'—'):key==='G'?(s.goals??'—'):key==='A'?(s.assists??'—'):key==='PTS'?(s.points??'—'):key==='+/-'?(s.plusMinus??'—'):key==='SOG'?(s.shots??'—'):key==='W'?(s.wins??'—'):key==='L'?(s.losses??'—'):key==='OT'?(s.otLosses??'—'):key==='SV%'?(s.savePctg!=null?Number(s.savePctg).toFixed(3):'—'):key==='GAA'?(s.goalsAgainstAvg!=null?Number(s.goalsAgainstAvg).toFixed(2):'—'):key==='SO'?(s.shutouts??'—'):s.saves??'—';return '<table><thead><tr>'+columns.map(c=>`<th>${c}</th>`).join('')+'</tr></thead><tbody>'+seasons.map(s=>'<tr>'+columns.map(c=>`<td>${esc(cell(s,c))}</td>`).join('')+'</tr>').join('')+'</tbody></table>'}
async function loadPlayerStats(player=playerSelections.stats){const btn=$('loadPlayerStats');if(!player){status('playerStatus','Search for and select a player by name first.','error');return}busy(btn,true,'Loading…');status('playerStatus','Loading player stats…');$('playerProfile').innerHTML='';$('playerStats').innerHTML='';$('seasonStats').innerHTML='';try{const d=await get(`/player/${encodeURIComponent(player.id)}/landing`),career=d.careerTotals?.regularSeason||{},featured=d.featuredStats?.regularSeason?.subSeason||{};playerSelections.stats={...player,name:[d.firstName?.default,d.lastName?.default].filter(Boolean).join(' ')||player.name,team:player.team||d.currentTeamAbbrev||'',position:player.position||d.position||''};$('statsSelected').textContent=`Selected: ${playerSelections.stats.name}${playerSelections.stats.team?' · '+playerSelections.stats.team:''}`;status('playerStatus',`${playerSelections.stats.name} · Career totals`,'success');$('playerProfile').innerHTML=d.headshot?`<img src="${esc(d.headshot)}" alt="${esc(playerSelections.stats.name)}" style="width:72px;height:72px;border-radius:50%;object-fit:cover;margin:12px 0">`:'';$('playerStats').innerHTML=metricRows(career).map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>Career ${esc(x[0].toLowerCase())}</span></div>`).join('')||'<div class="empty">No career totals were returned.</div>';const seasons=(d.seasonTotals||[]).filter(s=>s.gameTypeId===2&&s.leagueAbbrev==='NHL').sort((a,b)=>b.season-a.season);if(seasons.length)$('seasonStats').innerHTML=seasonTable(seasons,playerSelections.stats.position==='G');else if(Object.keys(featured).length)$('seasonStats').innerHTML='<div class="description" style="padding:14px">Most recent season: '+metricRows(featured).map(x=>`${esc(x[0])} ${esc(x[1])}`).join(' · ')+'</div>'}catch(e){status('playerStatus',e.message,'error')}finally{busy(btn,false)}}
async function loadPlayerLast10(player){const out=$('playerLast10');if(!out)return;out.innerHTML='<div class="description" style="padding:14px">Loading last 10 games…</div>';try{const seasons=seasonIdsForDate(dateStr(new Date())),logs=await Promise.all(seasons.map(async season=>{try{return(await get(`/player/${encodeURIComponent(player.id)}/game-log/${season}/2`)).gameLog||[]}catch{return []}})),games=[...new Map(logs.flat().map(g=>[`${g.gameDate}:${g.gameId||g.opponentAbbrev}`,g])).values()].sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10),goalie=player.position==='G';if(!games.length){out.innerHTML='<div class="description" style="padding:14px">No recent regular-season games are available for this player.</div>';return}const columns=goalie?['Date','Opponent','Decision','Saves','Shots against','GA','SV%','TOI']:['Date','Opponent','G','A','PTS','SOG','BLK','+/-','TOI'];const value=(g,c)=>c==='Date'?g.gameDate||'—':c==='Opponent'?g.opponentAbbrev||g.opponent||'—':c==='Decision'?g.decision||'—':c==='Saves'?g.saves??'—':c==='Shots against'?g.shotsAgainst??'—':c==='GA'?g.goalsAgainst??'—':c==='SV%'?g.savePctg==null?'—':Number(g.savePctg).toFixed(3):c==='G'?g.goals??0:c==='A'?g.assists??0:c==='PTS'?g.points??0:c==='SOG'?g.shots??0:c==='BLK'?g.blockedShots??g.blocked??'—':c==='+/-'?g.plusMinus??'—':g.toi||'—';out.innerHTML=`<h4 style="margin:18px 0 4px">Last 10 games</h4><div class="tablewrap"><table><thead><tr>${columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${games.map(g=>`<tr>${columns.map(c=>`<td>${esc(value(g,c))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}catch{out.innerHTML='<div class="description" style="padding:14px">Last 10 games could not be loaded right now.</div>'}}
$('loadPlayerStats').addEventListener('click',()=>loadPlayerStats());

const num=x=>Number(x)||0;
async function loadHistory(player=playerSelections.history) {
 const btn=$('loadHistory'),opp=$('opponent').value;
 if(!player){status('historyStatus','Search for and select a player by name first.','error');return}
 busy(btn,true,'Loading…');$('historySummary').innerHTML='';$('historyTable').innerHTML='';
 try{
  const landing=await get(`/player/${encodeURIComponent(player.id)}/landing`);
  const seasons=[...new Set((landing.seasonTotals||[]).filter(s=>s.gameTypeId===2&&s.leagueAbbrev==='NHL').map(s=>s.season).filter(Boolean))].sort((a,b)=>b-a);
  if(!seasons.length)throw Error('No regular-season game history is available.');
  const position=String(player.position||landing.position||'').toUpperCase(),isGoalie=position==='G'||position.includes('GOALIE');
  const requested=$('sample').value,needed=requested==='all'||requested==='two-seasons'?Infinity:Number(requested),matches=[];let seasonsChecked=0,failed=0;
  const readSeason=async season=>{try{const data=await get(`/player/${encodeURIComponent(player.id)}/game-log/${season}/2`);return(data.gameLog||[]).filter(g=>g.opponentAbbrev===opp||g.opponent===opp).map(g=>({...g,season}))}catch{failed++;return[]}};
  if(Number.isFinite(needed)){for(const season of seasons){seasonsChecked++;status('historyStatus',`Checking ${String(season).replace(/(\d{4})(\d{4})/,'$1–$2')}… ${matches.length} of ${needed} games found`);matches.push(...await readSeason(season));if(matches.length>=needed)break}}
  else if(requested==='two-seasons'){const recentSeasons=seasons.slice(0,2);seasonsChecked=recentSeasons.length;status('historyStatus',`Checking the last ${recentSeasons.length} NHL seasons…`);matches.push(...(await Promise.all(recentSeasons.map(readSeason))).flat())}
  else{for(let i=0;i<seasons.length;i+=4){const batch=seasons.slice(i,i+4);seasonsChecked+=batch.length;status('historyStatus',`Checking career history… ${seasonsChecked} of ${seasons.length} seasons`);matches.push(...(await Promise.all(batch.map(readSeason))).flat())}}
  if(failed===seasonsChecked&&!matches.length)throw Error('Could not load player game logs. Check the NHL data connection and try again.');
  matches.sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''));const shown=Number.isFinite(needed)?matches.slice(0,needed):matches;
  if(!matches.length){status('historyStatus',`No games against ${teams.find(t=>t[0]===opp)?.[1]||opp} were found in available regular seasons.`);return}
  const t={gp:shown.length,g:shown.reduce((n,x)=>n+num(x.goals),0),a:shown.reduce((n,x)=>n+num(x.assists),0),p:shown.reduce((n,x)=>n+num(x.points),0),s:shown.reduce((n,x)=>n+num(x.shots),0)};
  status('historyStatus',`${player.name} vs ${teams.find(x=>x[0]===opp)?.[1]||opp} · ${shown.length} games found across ${seasonsChecked} season${seasonsChecked===1?'':'s'}`,'success');
  if(isGoalie){
   const decisions=shown.map(g=>String(g.decision||g.result||'').toUpperCase()),wins=decisions.filter(x=>x==='W'||x==='WIN').length,losses=decisions.filter(x=>x==='L'||x==='LOSS').length,otLosses=decisions.filter(x=>x==='O'||x==='OT'||x==='OTL').length;
   const minutes=g=>{const bits=String(g.toi||'').split(':').map(Number);return bits.length===2&&bits.every(Number.isFinite)?bits[0]+bits[1]/60:bits.length===3&&bits.every(Number.isFinite)?bits[0]*60+bits[1]+bits[2]/60:0};
   const totalMinutes=shown.reduce((n,g)=>n+minutes(g),0),ga=shown.reduce((n,g)=>n+num(g.goalsAgainst),0),shotsAgainst=shown.reduce((n,g)=>n+num(g.shotsAgainst),0),saves=shown.reduce((n,g)=>n+(g.saves==null?Math.max(0,num(g.shotsAgainst)-num(g.goalsAgainst)):num(g.saves)),0),savePct=shotsAgainst?saves/shotsAgainst:null,gaa=totalMinutes?ga*60/totalMinutes:null;
   $('historySummary').innerHTML=[['Record',`${wins}–${losses}–${otLosses}`],['Games',shown.length],['Goals against',ga],['Goals-against average',gaa===null?'—':gaa.toFixed(2)],['Save percentage',savePct===null?'—':savePct.toFixed(3)],['Saves',saves],['Shots against',shotsAgainst]].map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>${esc(x[0])}</span></div>`).join('');
   $('historyTable').innerHTML='<table><thead><tr><th>Date</th><th>Season</th><th>Opponent</th><th>Decision</th><th>Saves</th><th>Shots against</th><th>Goals against</th><th>SV%</th><th>TOI</th></tr></thead><tbody>'+shown.map(g=>{const faced=num(g.shotsAgainst),against=num(g.goalsAgainst),sv=g.saves==null?Math.max(0,faced-against):num(g.saves),pct=faced?sv/faced:g.savePctg;return `<tr><td>${esc(g.gameDate||'—')}</td><td>${esc(String(g.season).replace(/(\d{4})(\d{4})/,'$1–$2'))}</td><td>${esc(g.opponentAbbrev||opp)}</td><td>${esc(g.decision||g.result||'—')}</td><td>${g.saves==null?sv:g.saves}</td><td>${g.shotsAgainst??'—'}</td><td>${g.goalsAgainst??'—'}</td><td>${pct==null?'—':Number(pct).toFixed(3)}</td><td>${esc(g.toi||'—')}</td></tr>`}).join('')+'</tbody></table>';
  }else{
   const pointPct=Math.round(100*shown.filter(g=>num(g.points)>0).length/shown.length);
   $('historySummary').innerHTML=[['Games',t.gp],['Goals',t.g],['Assists',t.a],['Points',t.p],['Shots',t.s],['Shots / game',(t.s/t.gp).toFixed(2)],['Games with a point',pointPct+'%']].map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>${esc(x[0])}</span></div>`).join('');
   $('historyTable').innerHTML='<table><thead><tr><th>Date</th><th>Season</th><th>Opponent</th><th>Goals</th><th>Assists</th><th>Points</th><th>Shots</th><th>TOI</th></tr></thead><tbody>'+shown.map(g=>`<tr><td>${esc(g.gameDate||'—')}</td><td>${esc(String(g.season).replace(/(\d{4})(\d{4})/,'$1–$2'))}</td><td>${esc(g.opponentAbbrev||opp)}</td><td>${num(g.goals)}</td><td>${num(g.assists)}</td><td>${num(g.points)}</td><td>${num(g.shots)}</td><td>${esc(g.toi||'—')}</td></tr>`).join('')+'</tbody></table>';
  }
 }catch(e){status('historyStatus',e.message,'error')}finally{busy(btn,false)}
}
$('loadHistory').addEventListener('click',()=>loadHistory());

let teamRows=[],activeDirectoryTeam='';
const recentFormCache=new Map();
function nhlSeasonIds(){const now=new Date(),year=now.getFullYear(),start=now.getMonth()>=6?year:year-1;return [Number(`${start}${start+1}`),Number(`${start-1}${start}`)]}
function formBadge(form){if(!form)return '';const badges=[];if(form.pointStreak>=3)badges.push(`<span class="hot-badge" role="img" aria-label="Hot: ${form.pointStreak}-game point streak" title="${form.pointStreak}-game point streak">🔥</span>`);if(form.shotStreak>=5)badges.push(`<span class="streak-badge" aria-label="${form.shotStreak}-game shots-on-goal streak" title="Shots on goal in ${form.shotStreak} straight games">SOG ${form.shotStreak}</span>`);return badges.join(' ')}
async function recentPlayerForm(player){
 const [current,previous]=nhlSeasonIds(),key=`${player.id}:${current}`;
 if(recentFormCache.has(key))return recentFormCache.get(key);
 const request=(async()=>{
  try{
   const first=await get(`/player/${encodeURIComponent(player.id)}/game-log/${current}/2`),games=[...(first.gameLog||[])];
   if(games.length<10){const prior=await get(`/player/${encodeURIComponent(player.id)}/game-log/${previous}/2`);games.push(...(prior.gameLog||[]))}
   games.sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''));const last=games.slice(0,10);
   if(!last.length)return null;
   let pointStreak=0,shotStreak=0;
   for(const game of games){if(num(game.points)<1)break;pointStreak++}
   for(const game of games){if(num(game.shots)<1)break;shotStreak++}
   return {pointStreak,shotStreak};
  }catch{return {unavailable:true}}
 })();recentFormCache.set(key,request);return request;
}
function teamLogo(ab){return `https://assets.nhle.com/logos/nhl/svg/${encodeURIComponent(ab)}_light.svg`}
async function loadTeamDefense(ab,season){
 const statusNode=$('teamDefenseStatus'),tableNode=$('teamDefenseTable');if(!statusNode||!tableNode)return;
 statusNode.textContent='Calculating season-to-date defense splits…';tableNode.innerHTML='';
 try{
  const data=await get(`/api/team-defense/${encodeURIComponent(ab)}/${season}`,45000);
  if(activeDirectoryTeam!==ab)return;
  const seasonLabel=String(data.season).replace(/(\d{4})(\d{4})/,'$1–$2');
  if(!data.gamesProcessed){statusNode.textContent=data.gamesScheduled?'Game details could not be loaded yet. Please try again shortly.':`No completed regular-season games for ${seasonLabel} yet.`;return}
  statusNode.textContent=`${data.team} · ${seasonLabel} · ${data.gamesProcessed} team games${data.failed?` · ${data.failed} game details unavailable`:''}`;
  const positions=[['Forwards',data.allowed.Forwards],['Defensemen',data.allowed.Defensemen],['Goalies',data.allowed.Goalies]];
  tableNode.innerHTML='<table><thead><tr><th>Opponent position</th><th>Shots allowed</th><th>SOG / game</th><th>Goals allowed</th><th>Goals / game</th><th>Points allowed</th><th>PTS / game</th></tr></thead><tbody>'+positions.map(([name,stats])=>`<tr><td><b>${name}</b></td><td>${stats.shots}</td><td>${(stats.shots/data.gamesProcessed).toFixed(1)}</td><td>${stats.goals||0}</td><td>${((stats.goals||0)/data.gamesProcessed).toFixed(2)}</td><td>${stats.points}</td><td>${(stats.points/data.gamesProcessed).toFixed(2)}</td></tr>`).join('')+'</tbody></table>';
 }catch(e){if(activeDirectoryTeam===ab)statusNode.textContent=e.message}
}
function renderTeamDirectory(){const q=$('teamDirectorySearch').value.trim().toLowerCase();$('teamDirectoryGrid').innerHTML=teams.filter(t=>`${t[0]} ${t[1]}`.toLowerCase().includes(q)).map(t=>{const record=teamRows.find(r=>(r.teamAbbrev?.default||r.teamAbbrev)===t[0]);return `<button class="directory-card" data-team="${t[0]}"><span class="directory-code">${t[0]}</span><span><b>${esc(t[1])}</b><small>${record?`${record.wins||0}–${record.losses||0}–${record.otLosses||0} · ${record.points||0} pts`:'Open team directory'}</small></span></button>`}).join('');document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>loadTeamRoster(b.dataset.team)))}
$('teamDirectorySearch').addEventListener('input',renderTeamDirectory);
function rosterDisplayName(p){const first=String(p.firstName?.default||p.firstName||'').trim(),last=String(p.lastName?.default||p.lastName||'').trim();return [first,last].filter(Boolean).join(' ')||String(p.name||'').trim()||'Player'}
function returnToTeamDirectory(){activeDirectoryTeam='';$('teamRosterPage').classList.add('hidden');$('teamDirectoryPage').classList.remove('hidden');$('directoryRoster').innerHTML='';$('directoryRosterStatus').textContent='';$('backToTeams').blur()}
$('backToTeams').addEventListener('click',returnToTeamDirectory);
function restoreTeamPlayerSections(){for(const [sectionId,homeId] of [['player','playerSectionHome'],['history','historySectionHome']]){const section=$(sectionId);if(!section)continue;section.classList.remove('team-player-detail');section.classList.add('hidden');$(homeId).append(section)}$('teamPlayerPage').classList.add('hidden');$('teamPlayerHero').innerHTML='';$('playerLast10').innerHTML='';$('teamRosterPage').classList.remove('hidden')}
function openTeamPlayer(p){
 $('teamRosterPage').classList.add('hidden');$('teamPlayerPage').classList.remove('hidden');$('teamPlayerTitle').textContent=p.name;$('teamPlayerMeta').textContent=`${teams.find(t=>t[0]===p.team)?.[1]||p.team} · ${p.position==='G'?'Goalie':p.position==='D'?'Defense':'Forward'}${p.sweaterNumber?` · #${p.sweaterNumber}`:''}`;
 $('teamPlayerHero').innerHTML=p.headshot?`<img class="team-player-avatar" src="${esc(p.headshot)}" alt="">`:'';
 $('playerSectionHost').append($('player'));$('historySectionHost').append($('history'));$('player').classList.remove('hidden');$('history').classList.remove('hidden');$('player').classList.add('team-player-detail');$('history').classList.add('team-player-detail');
 selectPlayer('stats',p);selectPlayer('history',p);$('opponent').value=teams.find(t=>t[0]!==p.team)?.[0]||'';loadPlayerStats(p);loadPlayerLast10(p);status('historyStatus','Choose an opponent and load this player’s matchup history.');$('backToRoster').focus();
}
$('backToRoster').addEventListener('click',restoreTeamPlayerSections);
function compactName(name){const parts=String(name||'').trim().split(/\s+/).filter(Boolean);return parts.length>1?`${parts[0][0]}. ${parts[parts.length-1]}`:name||'Player'}
function renderTeamSpecialStats(data){
 const output=$('teamSpecialStats'),goalLeader=data.emptyNetLeaders?.[0],tiedLeaders=goalLeader?data.emptyNetLeaders.filter(p=>p.goals===goalLeader.goals):[],timeLeaders=data.goaliePulledLeaders||[];
 const goalHtml=goalLeader?`<div class="special-leader"><h5>Most empty-net goals</h5><strong>${tiedLeaders.map(p=>esc(compactName(p.name))).join(', ')}</strong><span>${goalLeader.goals} goal${goalLeader.goals===1?'':'s'} · ${data.gamesProcessed} games</span></div>`:'<div class="special-leader"><h5>Most empty-net goals</h5><strong>No goals recorded</strong><span>No completed empty-net goals in the available sample.</span></div>';
 const table=timeLeaders.length?`<div class="tablewrap"><table><thead><tr><th>Player</th><th>Time against pulled goalie</th></tr></thead><tbody>${timeLeaders.map(p=>`<tr><td><b>${esc(compactName(p.name))}</b></td><td>${(Number(p.minutes)||0).toFixed(1)} min</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No goalie-pull shift time is available in the completed-game sample.</div>';
 output.innerHTML=`<div class="special-leader-grid">${goalHtml}<div class="special-leader"><h5>Sample coverage</h5><strong>${data.shiftGames} of ${data.gamesScheduled}</strong><span>completed-game shift charts processed · ${data.failed} game requests incomplete</span></div></div><h4 style="margin:18px 0 0">Most time with the opposing goalie pulled</h4>${table}`;
 status('teamSpecialStatus',data.gamesProcessed?`Season sample: ${data.gamesProcessed} completed games · shift-based goalie-pull time from ${data.shiftGames} games. First analysis can take a little longer; results are cached for 30 minutes.`:'No completed regular-season games are available for this team yet.',data.gamesProcessed?'success':'');
}
async function loadTeamSpecialStats(){
 const ab=activeDirectoryTeam;if(!ab)return;
 const button=$('loadTeamSpecialStats'),[season,previous]=nhlSeasonIds();busy(button,true,'Analyzing…');$('teamSpecialStats').innerHTML='';status('teamSpecialStatus','Analyzing empty-net goals and shift charts for this season…');
 try{let data=await get(`/api/team-special-stats/${encodeURIComponent(ab)}/${season}`,120000);if(!data.gamesProcessed&&!data.gamesScheduled){status('teamSpecialStatus','No completed games yet this season · Loading the latest completed season…');data=await get(`/api/team-special-stats/${encodeURIComponent(ab)}/${previous}`,120000)}if(activeDirectoryTeam===ab)renderTeamSpecialStats(data)}
 catch(e){if(activeDirectoryTeam===ab)status('teamSpecialStatus',e.message,'error')}
 finally{busy(button,false)}
}
function playerOnIR(player){const values=[player.rosterStatus,player.status,player.injuryStatus,player.transactionType,player.listingStatus].filter(x=>typeof x==='string').join(' ').toLowerCase();return player.injuredReserve===true||player.isOnIR===true||player.ir===true||/\b(ir|ltir|injured reserve|long[- ]term injured reserve)\b/.test(values)}
$('loadTeamSpecialStats').addEventListener('click',loadTeamSpecialStats);
async function loadTeamRoster(ab){
 activeDirectoryTeam=ab;$('teamDirectoryPage').classList.add('hidden');$('teamRosterPage').classList.remove('hidden');$('rosterPageTitle').textContent=teams.find(t=>t[0]===ab)?.[1]||ab;$('directoryRoster').innerHTML='';status('directoryRosterStatus',`Loading ${teams.find(t=>t[0]===ab)?.[1]||ab} roster…`);
 try{
  const d=await get(`/roster/${encodeURIComponent(ab)}/current`),groups=[['Forwards',d.forwards||[]],['Defense',d.defensemen||d.defense||[]],['Goalies',d.goalies||[]]],irRoster=[d.injuredReserve,d.injuredReservePlayers,d.irPlayers].find(Array.isArray)||[],rosterIds=new Set(groups.flatMap(g=>g[1]).map(p=>String(p.id??p.playerId))),irOnly=irRoster.filter(p=>!rosterIds.has(String(p.id??p.playerId)));if(irOnly.length)groups.push(['Injured reserve',irOnly]);const irIds=new Set(irRoster.map(p=>String(p.id??p.playerId)));const total=groups.reduce((n,g)=>n+g[1].length,0);
  if(!total)throw Error('No roster was returned for this team.');
  const players=groups.flatMap(g=>g[1]).map(p=>({id:String(p.id??p.playerId),name:rosterDisplayName(p),team:ab,position:p.positionCode||'',headshot:p.headshot||'',sweaterNumber:p.sweaterNumber,injured:irIds.has(String(p.id??p.playerId))||playerOnIR(p)}));
  status('directoryRosterStatus',`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · Checking recent form…`);
  $('directoryRoster').innerHTML='<p class="form-legend">🔥 3+ consecutive games with a point · SOG streaks of 5+ games are labeled separately · 🩹 injured reserve</p>'+groups.filter(g=>g[1].length).map(([label,rawPlayers])=>`<div class="roster-group"><h4>${label} · ${rawPlayers.length}</h4><div class="roster-grid">${rawPlayers.map(p=>{const player=players.find(x=>x.id===String(p.id??p.playerId));return `<div class="roster-player">${player.headshot?`<img src="${esc(player.headshot)}" alt="" loading="lazy">`:''}<span class="grow"><span class="roster-name"><button class="roster-player-name" type="button" data-roster-player="${esc(player.id)}">${esc(player.name)}</button>${player.injured?'<span class="ir-badge" role="img" aria-label="Injured reserve" title="Listed on injured reserve">🩹</span>':''}<span class="form-marker" data-form-player="${esc(player.id)}" aria-live="polite"><span class="form-pending">checking</span></span></span><small>${player.position?esc(player.position)+' · ':''}${player.sweaterNumber?`#${esc(player.sweaterNumber)}`:''}</small></span></div>`}).join('')}</div></div>`).join('')+`<section class="defense-panel"><div class="panelhead"><div><h4>Defense vs. opponent position</h4><p>Season-to-date totals and per-game rates for players facing this club.</p></div><span class="pill">${String(nhlSeasonIds()[0]).replace(/(\d{4})(\d{4})/,'$1–$2')}</span></div><div id="teamDefenseStatus" class="status is-loading" role="status">Loading position splits…</div><div id="teamDefenseTable" class="tablewrap"></div></section>`;
  players.forEach(p=>document.querySelector(`[data-roster-player="${CSS.escape(p.id)}"]`)?.addEventListener('click',()=>openTeamPlayer(p)));
  loadTeamDefense(ab,nhlSeasonIds()[0]);
  const skaters=players.filter(p=>p.position!=='G'),hotCount={value:0},failedCount={value:0};let done=0,next=0;
  const worker=async()=>{while(next<skaters.length){const player=skaters[next++],form=await recentPlayerForm(player);done++;const marker=document.querySelector(`[data-form-player="${CSS.escape(player.id)}"]`);if(marker&&activeDirectoryTeam===ab){if(form?.unavailable){failedCount.value++;marker.innerHTML='<span class="form-pending" title="Recent form could not be loaded">—</span>'}else{marker.innerHTML=formBadge(form);if(marker.querySelector('.hot-badge'))hotCount.value++}status('directoryRosterStatus',`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · Checking recent form ${done}/${skaters.length}…`)}}};
  await Promise.all(Array.from({length:Math.min(8,skaters.length)},worker));
  if(activeDirectoryTeam===ab)status('directoryRosterStatus',failedCount.value===skaters.length&&skaters.length?`Roster loaded · Recent form is unavailable right now.`:`${teams.find(t=>t[0]===ab)?.[1]||ab} · ${total} players · ${hotCount.value?`${hotCount.value} player${hotCount.value===1?'':'s'} trending 🔥`:'Recent form checked'}`,failedCount.value===skaters.length?'':'success');
 }catch(e){if(activeDirectoryTeam===ab)status('directoryRosterStatus',e.message,'error')}
}

async function loadTeams(){cache.delete(api+'/standings/now');const btn=$('loadTeams');busy(btn,true,'Loading…');status('teamStatus','Loading team stats…');try{const d=await get('/standings/now');teamRows=d.standings||[];if(!teamRows.length)throw Error('No team statistics were returned.');drawTeams();renderTeamDirectory();status('teamStatus',`${teamRows.length} teams · standings updated ${d.standingsDate||'today'}`,'success')}catch(e){status('teamStatus',e.message,'error')}finally{busy(btn,false)}}
function drawTeams(){const q=$('teamFilter').value.trim().toLowerCase(),rows=teamRows.filter(t=>`${t.teamName?.default||''} ${t.teamAbbrev?.default||t.teamAbbrev||''} ${t.divisionName||''} ${t.conferenceName||''}`.toLowerCase().includes(q));$('teamsTable').innerHTML=rows.length?'<table><thead><tr><th>Team</th><th>Division</th><th>GP</th><th>W</th><th>L</th><th>OT</th><th>PTS</th><th>Points %</th><th>GF</th><th>GA</th><th>DIFF</th></tr></thead><tbody>'+rows.map(t=>{const ab=t.teamAbbrev?.default||t.teamAbbrev||'';return `<tr><td><b>${esc(t.teamName?.default||ab)}</b></td><td>${esc(t.divisionName||'—')}</td><td>${esc(t.gamesPlayed??'—')}</td><td>${esc(t.wins??'—')}</td><td>${esc(t.losses??'—')}</td><td>${esc(t.otLosses??'—')}</td><td><b>${esc(t.points??'—')}</b></td><td>${t.pointPctg!=null?`${(100*t.pointPctg).toFixed(1)}%`:'—'}</td><td>${esc(t.goalFor??'—')}</td><td>${esc(t.goalAgainst??'—')}</td><td>${esc(t.goalDifferential??'—')}</td></tr>`}).join('')+'</tbody></table>':'<div class="empty">No team records found.</div>'}
$('loadTeams').addEventListener('click',loadTeams);$('teamFilter').addEventListener('input',drawTeams);


function seasonIdsForDate(date){const d=new Date(`${date}T12:00:00`),year=d.getFullYear(),start=d.getMonth()>=6?year:year-1;return [Number(`${start}${start+1}`),Number(`${start-1}${start}`)]}
function hitRate(games,key,threshold){return games.length?games.filter(g=>num(g[key])>=threshold).length/games.length:null}
function weightedRate(parts){const usable=parts.filter(x=>x.rate!=null&&x.weight>0);return usable.length?usable.reduce((n,x)=>n+x.rate*x.weight,0)/usable.reduce((n,x)=>n+x.weight,0):0}
function pickPropLabel(key,threshold){return key==='points'?'1+ point':key==='shots'?`${threshold}+ shots on goal`:'1+ goal'}
let activePickType='shots',pickLists={shots:[],points:[],goals:[]},pickDefense={};
function renderPickCards(){const picks=pickLists[activePickType]||{},defense=pickDefense;$('picksOut').innerHTML=picks.length?picks.map((p,i)=>{const oppSplit=defense[p.opp],posKey=p.position==='D'?'Defensemen':'Forwards',split=oppSplit?.allowed?.[posKey],allowedKey=p.prop.key==='goals'?'goals':p.prop.key==='points'?'points':'shots',rate=split&&oppSplit.gamesProcessed?split[allowedKey]/oppSplit.gamesProcessed:null;return `<article class="pick-card"><span class="pick-rank">#${i+1}</span><h4>${esc(p.name)}</h4><div class="pick-meta">${esc(p.team)} · ${esc(p.position==='D'?'Defense':'Forward')} vs ${esc(p.opp)}</div><div class="pick-prop">${esc(pickPropLabel(p.prop.key,p.prop.threshold))}</div><div class="pick-rate">${Math.round(p.rate*100)}% empirical estimate</div><div class="pick-detail">Recent 10: ${p.recentHits}/${p.recent.length||'—'} · This season: ${p.currentHits}/${p.current.length||'—'} · Previous: ${p.priorHits}/${p.prior.length||'—'}</div><div class="pick-detail">Vs opponent, last 2 seasons: ${p.h2h.length?`${p.h2hHits}/${p.h2h.length}`:'no games in sample'}${rate!=null?` · Opponent allows ${rate.toFixed(2)} ${allowedKey} per ${posKey.toLowerCase()} player/game (${oppSplit.gamesProcessed} team games)`:''}</div>${p.recent.length<5?'<div class="pick-detail pick-warn">Limited recent sample</div>':''}</article>`}).join(''):'<div class="empty">No qualified player trends are available for this prop and slate yet.</div>'}
document.querySelectorAll('[data-pick-view]').forEach(button=>button.addEventListener('click',()=>{activePickType=button.dataset.pickView;document.querySelectorAll('[data-pick-view]').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-selected',String(x===button))});renderPickCards()}));
async function buildDailyPicks(){const btn=$('buildPicks'),date=$('picksDate').value;busy(btn,true,'Researching…');pickLists={shots:[],points:[],goals:[]};pickDefense={};renderPickCards();status('picksStatus','Loading the slate…');try{
 const slateData=await get(`/score/${encodeURIComponent(date)}`),games=(slateData.games||[]).filter(g=>!['OFF','FINAL'].includes(g.gameState));if(!games.length){status('picksStatus','No upcoming games are scheduled for this date. Select a slate with games that have not started.');return}
 const teamsPlaying=[...new Set(games.flatMap(g=>[g.homeTeam?.abbrev,g.awayTeam?.abbrev]).filter(Boolean))],seasonIds=seasonIdsForDate(date),rosters=await Promise.all(teamsPlaying.map(async ab=>{try{const d=await get(`/roster/${encodeURIComponent(ab)}/current`);return {ab,players:[...(d.forwards||[]),...(d.defensemen||d.defense||[])].map(p=>({id:String(p.id??p.playerId),name:[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||p.name||'Player',team:ab,position:p.positionCode||'',headshot:p.headshot||''})).filter(p=>p.id&&p.id!=='undefined')}}catch{return {ab,players:[]}}}));
 const players=[...new Map(rosters.flatMap(x=>x.players).map(p=>[p.id,p])).values()];if(!players.length)throw Error('Could not load skater rosters for this slate.');status('picksStatus',`Comparing ${players.length} skaters across ${games.length} games · loading two seasons of game logs…`);
 const logData=new Map();let next=0,finished=0;const worker=async()=>{while(next<players.length){const player=players[next++];const logs=await Promise.all(seasonIds.map(async season=>{try{return(await get(`/player/${encodeURIComponent(player.id)}/game-log/${season}/2`)).gameLog||[]}catch{return []}}));logData.set(player.id,logs.map(list=>list.filter(g=>(g.gameDate||'')<date).sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||''))));finished++;if(finished%12===0||finished===players.length)status('picksStatus',`Comparing ${players.length} skaters · game logs ${finished}/${players.length}…`)} };await Promise.all(Array.from({length:Math.min(12,players.length)},worker));
  const candidates=[];for(const game of games){const home=game.homeTeam?.abbrev,away=game.awayTeam?.abbrev;for(const player of players.filter(p=>p.team===home||p.team===away)){const opp=player.team===home?away:home,[currentAll,prior]=logData.get(player.id)||[[],[]],current=currentAll.slice(0,1000),recent=[...current,...prior].sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10),h2h=[...currentAll,...prior].filter(g=>g.opponentAbbrev===opp||g.opponent===opp).sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10);if(recent.length<3)continue;const props=[{key:'points',threshold:1},{key:'shots',threshold:2},{key:'shots',threshold:3},{key:'goals',threshold:1}];for(const prop of props){const r=hitRate(recent,prop.key,prop.threshold),c=hitRate(current,prop.key,prop.threshold),p=hitRate(prior,prop.key,prop.threshold),h=hitRate(h2h,prop.key,prop.threshold),rate=weightedRate([{rate:r,weight:.50},{rate:c,weight:.30},{rate:p,weight:.20}]);const evidence=[recent.length,current.length,prior.length].reduce((a,n)=>a+n,0);if(evidence<6)continue;candidates.push({name:player.name,team:player.team,position:player.position,opp,prop,rate,recent,current,prior,h2h,recentHits:recent.filter(g=>num(g[prop.key])>=prop.threshold).length,currentHits:current.filter(g=>num(g[prop.key])>=prop.threshold).length,priorHits:prior.filter(g=>num(g[prop.key])>=prop.threshold).length,h2hHits:h2h.filter(g=>num(g[prop.key])>=prop.threshold).length,evidence})}}}
 const bestFor=key=>{const best=new Map();for(const p of candidates.filter(x=>x.prop.key===key).sort((a,b)=>b.rate-a.rate||b.evidence-a.evidence)){const k=p.name+':'+p.team;if(!best.has(k))best.set(k,p)}return [...best.values()].slice(0,10)};pickLists={shots:bestFor('shots'),points:bestFor('points'),goals:bestFor('goals')};const allTop=[...pickLists.shots,...pickLists.points,...pickLists.goals];if(!allTop.length){status('picksStatus','There is not enough regular-season player history yet to form top 10 lists for this slate.');return}renderPickCards();status('picksStatus',`Built separate SOG, points, and goals lists from ${players.length} skaters · estimates weight last 10 games 50%, this season 30%, previous season 20%. Loading opponent position splits…`,'success');
 const opponents=[...new Set(allTop.map(p=>p.opp))];let dn=0;await Promise.all(opponents.map(async opp=>{try{pickDefense[opp]=await get(`/api/team-defense/${encodeURIComponent(opp)}/${seasonIds[0]}`,45000)}catch{}dn++;status('picksStatus',`Top 10 lists ready · opponent position splits ${dn}/${opponents.length}…`)}));renderPickCards();status('picksStatus',`Top 10 lists ready · ${players.length} skaters analyzed · SOG, points, and goals projections show separate history and sample counts. Defense splits use completed games in the selected season.`,'success');
 }catch(e){status('picksStatus',e.message,'error')}finally{busy(btn,false)}}
$('picksDate').value=dateStr(new Date());$('buildPicks').addEventListener('click',buildDailyPicks);
async function recentTeamGames(team,slateDate){const seasons=seasonIdsForDate(slateDate),responses=await Promise.all(seasons.map(async season=>{try{return(await get(`/club-schedule-season/${encodeURIComponent(team)}/${season}`)).games||[]}catch{return []}})),currentStart=Number(String(seasons[0]).slice(0,4));return [...new Map(responses.flat().filter(g=>g.gameType===2&&['OFF','FINAL'].includes(g.gameState)&&(g.gameDate||'')<slateDate).map(g=>[String(g.id),{...g,currentSeason:Number(String(g.id).slice(0,4))===currentStart}])).values()].sort((a,b)=>(b.gameDate||'').localeCompare(a.gameDate||'')).slice(0,10)}
function modelHitRate(history,key,threshold,prior){if(history.length<3)return null;const current=history.filter(g=>g.currentSeason),previous=history.filter(g=>!g.currentSeason),rate=games=>games.length?games.filter(g=>num(g[key])>=threshold).length/games.length:null,lastFive=history.slice(0,5),recent=rate(lastFive),currentRate=rate(current),previousRate=rate(previous);let baselineRate=currentRate??previousRate??prior;if(currentRate!=null&&previousRate!=null){const currentWeight=current.length/(current.length+2);baselineRate=currentRate*currentWeight+previousRate*(1-currentWeight)}const formRate=recent==null?baselineRate:recent*.55+baselineRate*.45,effectiveSample=current.length+previous.length*.65;return Math.max(.08,Math.min(.9,(formRate*effectiveSample+prior*4)/(effectiveSample+4)))}
function enumerateModelParlays(legs){const bands=[{min:2,max:2.49,label:'2× estimated return'},{min:2.5,max:2.99,label:'2.5× estimated return'},{min:3,max:3.99,label:'3× estimated return'},{min:4,max:4.99,label:'4× estimated return'},{min:5,max:7,label:'5× estimated return'}],byGame=new Map();for(const leg of legs){if(leg.probability<.12||leg.probability>.9)continue;const list=byGame.get(leg.fixtureId)||[];list.push(leg);byGame.set(leg.fixtureId,list)}const pool=[...byGame.values()].flatMap(list=>[...list.filter(x=>x.market==='Team win').sort((a,b)=>b.probability-a.probability).slice(0,1),...list.filter(x=>x.market!=='Team win').sort((a,b)=>b.probability-a.probability).slice(0,2)]).sort((a,b)=>b.probability-a.probability).slice(0,36),picks=[],seen=new Set();for(const band of bands){let best=null;for(const requireMix of [true,false]){let nodes=0;function visit(start,chosen,odds,fixtures){if(++nodes>180000)return;if(chosen.length>=2&&odds>=band.min&&odds<=band.max){const hasTeam=chosen.some(x=>x.market==='Team win'),hasPlayer=chosen.some(x=>x.market!=='Team win'),key=chosen.map(x=>x.id).sort().join('|');if((!requireMix||(hasTeam&&hasPlayer))&&!seen.has(key)&&(!best||odds<best.odds))best={band:band.label,legs:[...chosen],odds,probability:1/odds,key}}if(chosen.length===6||odds>=band.max)return;for(let i=start;i<pool.length;i++){const leg=pool[i];if(fixtures.has(leg.fixtureId))continue;const nextOdds=odds/leg.probability;if(nextOdds>band.max)continue;const nextFixtures=new Set(fixtures);nextFixtures.add(leg.fixtureId);visit(i+1,[...chosen,leg],nextOdds,nextFixtures)}}visit(0,[],1,new Set());if(best)break}if(best){seen.add(best.key);picks.push(best)}}return picks}
function renderAutoParlays(picks){$('betCombos').innerHTML=picks.length?picks.map((p,i)=>`<article class="pick-card"><span class="pick-rank">#${i+1}</span><h4>${esc(p.band)}</h4><div class="pick-rate">${p.odds.toFixed(2)}×</div><div class="pick-detail">${(100*p.probability).toFixed(1)}% model-estimated hit chance · $10 at estimated fair value: $${(10*p.odds).toFixed(2)} return</div>${p.legs.map(x=>`<div class="pick-detail" style="margin-top:8px"><b>${esc(x.market)}</b> · ${esc(x.selection)} · ${Math.round(x.probability*100)}% estimated hit rate (${x.sample} game sample; ${x.sampleDetail})</div>`).join('')}</article>`).join(''):'<div class="empty">There are not enough recent game records to form five distinct parlays for this slate.</div>'}
let autoParlayDate='',autoParlayPromise=null;
async function loadAutoDailyParlays(force=false){
 const date=$('betDate').value;
 if(autoParlayPromise)return autoParlayPromise;
 if(!force&&autoParlayDate===date)return;
 const button=$('buildBetCombos');busy(button,true,'Analyzing game history…');$('betCombos').innerHTML='';status('betStatus','Loading today’s NHL slate and recent team schedules…');
 autoParlayPromise=(async()=>{try{
  const slate=await get(`/score/${encodeURIComponent(date)}`),games=(slate.games||[]).filter(g=>!['OFF','FINAL'].includes(g.gameState));
  if(!games.length){status('betStatus','No upcoming NHL games are available for this date.');return}
  const teamAbbrevs=[...new Set(games.flatMap(g=>[g.homeTeam?.abbrev,g.awayTeam?.abbrev]).filter(Boolean))];
  const teamGames=Object.fromEntries(await Promise.all(teamAbbrevs.map(async team=>[team,await recentTeamGames(team,date)])));
  const boxscoreGames=[...new Map(Object.values(teamGames).flat().map(g=>[String(g.id),g])).values()];
  const rosterResults=await Promise.all(teamAbbrevs.map(async team=>{try{
   const data=await get(`/roster/${encodeURIComponent(team)}/current`);
   const players=[...(data.forwards||[]),...(data.defensemen||data.defense||[])].map(p=>({id:String(p.id??p.playerId),name:[p.firstName?.default||p.firstName,p.lastName?.default||p.lastName].filter(Boolean).join(' ')||p.name||'Player',team,position:p.positionCode||''})).filter(p=>p.id&&p.id!=='undefined');
   return [team,players];
  }catch{return [team,[]]}}));
  const rosters=Object.fromEntries(rosterResults),currentPlayers=new Map(Object.values(rosters).flat().map(p=>[p.id,p]));
  status('betStatus',`Reading recent game boxes for ${teamAbbrevs.length} teams…`);
  const boxscores=new Map();let cursor=0,failed=0;
  const worker=async()=>{while(cursor<boxscoreGames.length){const game=boxscoreGames[cursor++];try{boxscores.set(String(game.id),await get(`/gamecenter/${encodeURIComponent(game.id)}/boxscore`,18000))}catch{failed++}}};
  await Promise.all(Array.from({length:Math.min(8,boxscoreGames.length)},worker));
  const playerHistory=new Map();
  for(const game of boxscoreGames){const box=boxscores.get(String(game.id));if(!box)continue;const groups=box.playerByGameStats||{},rows=['awayTeam','homeTeam'].flatMap(side=>['forwards','defense'].flatMap(group=>groups[side]?.[group]||[]));
   for(const row of rows){
    const id=String(row.playerId??row.id??'');if(!currentPlayers.has(id))continue;
    const goals=num(row.goals),assists=num(row.assists),entry={date:game.gameDate||'',currentSeason:Number(String(game.id).slice(0,4))===Number(String(seasonIdsForDate(date)[0]).slice(0,4)),points:num(row.points)||goals+assists,shots:num(row.shots??row.sog),blockedShots:num(row.blockedShots??row.blocked??0)};
    const history=playerHistory.get(id)||[];history.push(entry);playerHistory.set(id,history);
   }
  }
  for(const history of playerHistory.values())history.sort((a,b)=>b.date.localeCompare(a.date));
  const legs=[];
  for(const game of games){
   const fixtureId=String(game.id),home=game.homeTeam?.abbrev,away=game.awayTeam?.abbrev;
   const recordRate=team=>{const rows=teamGames[team]||[];if(!rows.length)return .5;const wins=rows.filter(g=>{const isHome=g.homeTeam?.abbrev===team;return Number(isHome?g.homeTeam?.score??g.homeScore:g.awayTeam?.score??g.awayScore)>Number(isHome?g.awayTeam?.score??g.awayScore:g.homeTeam?.score??g.homeScore)}).length;return(wins+1)/(rows.length+2)};
   const homeRate=recordRate(home),awayRate=recordRate(away),homeLogit=(homeRate-awayRate)*2.4+.16,homeProbability=Math.max(.22,Math.min(.78,1/(1+Math.exp(-homeLogit))));
   for(const [team,probability]of [[home,homeProbability],[away,1-homeProbability]]){const rows=teamGames[team]||[],currentCount=rows.filter(g=>g.currentSeason).length;legs.push({id:`${fixtureId}:team:${team}`,fixtureId,probability,market:'Team win',selection:`${team} to win (${rows.length}-game team form)`,sample:rows.length,sampleDetail:`${currentCount} this season`})}
   const playerLegs=[];
   for(const team of [home,away])for(const player of rosters[team]||[]){
    const history=(playerHistory.get(player.id)||[]).slice(0,10);if(history.length<3)continue;
    const props=[{key:'shots',threshold:2,label:'2+ shots on goal',market:'Shots on goal',prior:.58},{key:'blockedShots',threshold:1,label:'1+ blocked shot',market:'Blocked shots',prior:.42},{key:'points',threshold:1,label:'1+ point',market:'Player points',prior:.37}];
    for(const prop of props){const probability=modelHitRate(history,prop.key,prop.threshold,prop.prior);if(probability!=null)playerLegs.push({id:`${fixtureId}:${player.id}:${prop.key}`,fixtureId,probability,market:prop.market,selection:`${player.name} · ${prop.label} (${team})`,sample:history.length,sampleDetail:`${history.filter(g=>g.currentSeason).length} this season`})}
   }
   legs.push(...playerLegs.sort((a,b)=>b.probability-a.probability).slice(0,12));
  }
  const picks=enumerateModelParlays(legs);renderAutoParlays(picks);autoParlayDate=date;
  status('betStatus',`${picks.length} parlays built from NHL team and player game histories across ${boxscores.size} recent games${failed?` (${failed} game boxes unavailable)`:''}. Return multiples are statistical estimates, not sportsbook odds.`,'success');
 }catch(error){status('betStatus',error.message||'Could not build statistical parlays from NHL game data.','error')}
 finally{busy(button,false);autoParlayPromise=null}})();return autoParlayPromise;
}
$('betDate').value=dateStr(new Date());try{localStorage.removeItem('pp_odds_api_key');localStorage.removeItem('pp_players')}catch{};$('betDate').addEventListener('change',()=>loadAutoDailyParlays(true));$('buildBetCombos').addEventListener('click',()=>loadAutoDailyParlays(true));document.querySelector('[data-tab="bets"]').addEventListener('click',()=>loadAutoDailyParlays());
renderTeamDirectory();
async function prepareDashboard(){
 const splash=$('startupLoader'),message=$('startupMessage');
 $('enterDashboard').addEventListener('click',()=>splash.classList.add('hidden'));
 if(proxyServer){
  const deadline=Date.now()+60000;let ready=false;
  while(Date.now()<deadline){
   try{await fetchJson('/api/health',3000);ready=true;break}catch{}
   message.textContent='Waking up the rink… This can take about a minute.';
   await new Promise(resolve=>setTimeout(resolve,2000));
  }
  if(!ready){splash.classList.add('hidden');status('scoreStatus','The server is still waking up. Tap Load scoreboard to try again.','error');return}
 }
 message.textContent='Loading today’s scoreboard…';
 await loadScores();updateScoreboardLast10();
}
prepareDashboard();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
